### ISSUE TITLE
Lookup holding location using PULFA physloc codes

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1001]
Depends on https://github.com/pulibrary/marc_liberation/issues/210

**Comment by jpstroop** [comment]
@shaune might have the most complete picture here, if you can explain the Plum use case to him. I think there are only around six or eight codes, and they all probably can be mapped to either Firestone RBSC or Mudd.

**Comment by sdellis** [comment]
@escowles I'm not clear on what Digital Locations are, but [here's where we map the EAD physloc info to delivery locations and labels](https://github.com/pulibrary/pulfa/blob/development/webapp/xsl/lib.xsl#L87-L129). Does that help?

**Comment by escowles** [comment]
@sdellis Thanks — that's definitely helpful.

Digital Locations are the subset of Delivery Locations that have been flagged as having digital content, and we use those for Plum's location field.

**Comment by jpstroop** [comment]
Thanks @sdellis!
