### ISSUE TITLE
Remove access rights text from create new scanned book page

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#101]

**Comment by escowles** [comment]
I opened a PR in curation_concerns to make a partial for just the permissions note, to avoid having to copy and update a significant partial:

https://github.com/projecthydra-labs/curation_concerns/pull/409

**Comment by escowles** [comment]
projecthydra-labs/curation_concerns#409 is merged, but I wasn't able to get plum to use the current master branch without doing all the updates to CC/HW/PCDM that @tpendragon is going to do, so I'll wait.
