### ISSUE TITLE
Sipity Completion Notifications Column Type Mismatch

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1016]
When trying to look up the users to notify when an object is completed, Sipity is doing this query:

```
SELECT "users".*
FROM "users"
WHERE "users"."id" IN (
    SELECT "sipity_agents"."proxy_for_id"
    FROM "sipity_agents"
    WHERE ("sipity_agents"."id" IN (
        SELECT "sipity_workflow_responsibilities"."agent_id"
        FROM "sipity_workflow_responsibilities"
        WHERE "sipity_workflow_responsibilities"."workflow_role_id" IN (
            SELECT "sipity_workflow_roles"."id"
            FROM "sipity_workflow_roles"
            WHERE "sipity_workflow_roles"."role_id" IN (8)))
        OR "sipity_agents"."id" IN (
            SELECT "sipity_entity_specific_responsibilities"."agent_id"
            FROM "sipity_entity_specific_responsibilities"
            WHERE "sipity_entity_specific_responsibilities"."workflow_role_id" IN (
                SELECT "sipity_workflow_roles"."id"
                FROM "sipity_workflow_roles"
                WHERE "sipity_workflow_roles"."role_id" IN (8))
        AND "sipity_entity_specific_responsibilities"."entity_id" = '6472'))
    AND "sipity_agents"."proxy_for_type" = 'User')
):
```

The problem is that `users.id` is an integer but `sipity_agents.proxy_for_id` is a string.

**Comment by escowles** [comment]
It looks like `sipity_agents.proxy_for_id` can either be an integer, or a string like `admin` or `registered`.  Trying to complete a record in staging or production triggers this error, but I am not seeing it locally.

**Comment by tpendragon** [comment]
This is probably a difference between using postgres and the much less restrictive sqlite. I wonder if we should just start using postgres for development?

**Comment by escowles** [comment]
Yep, I setup Postgres locally, and I can confirm that I'm now seeing the error with any state change.

**Comment by escowles** [comment]
I upgraded to the latest CC and tried to figure out how to cast the user.id to a varchar (surely this is possible).

Tracking with a CC ticket: https://github.com/projecthydra/curation_concerns/issues/1152
