### ISSUE TITLE
Hyrax branch needs Visibility options from Plum

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1025]
Hyrax:
![screen shot 2017-02-23 at 1 15 07 pm](https://cloud.githubusercontent.com/assets/999701/23272650/21ef8ba2-f9ca-11e6-8811-f15210cd4cf5.png)

Plum:

![screen shot 2017-02-23 at 1 15 57 pm](https://cloud.githubusercontent.com/assets/999701/23272680/3bff90b4-f9ca-11e6-9492-640c89db9ff4.png)

And Change "Open Access" to just "Open" and the following text to "Open the the world. Anyone can view."

**Comment by tpendragon** [comment]
Fixed.
