### ISSUE TITLE
Save Work box floats to right when I scroll down

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1027]
It also flickers as I scroll (screen shot can't show that, but you can see how the position changes).

![screen shot 2017-02-23 at 1 18 55 pm](https://cloud.githubusercontent.com/assets/999701/23272873/ea49bbb8-f9ca-11e6-8ca4-c0f4261fa902.png)

**Comment by tpendragon** [comment]
Oh, yeah, I actually fiddled with this one for a while. I'm pretty sure it's a bug in Hyrax too, and a result of the box changing to fixed positioning. May be able to fix with some JS.

**Comment by tpendragon** [comment]
Fixed.
