### ISSUE TITLE
Do we really need the "Additional Fields" toggle?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1030]
It's OK w/ me, but feels like clutter for not that much more--especially w/ Access Controls off to the side.

**Comment by tpendragon** [comment]
Yeah, I wondered about this too. If there are a significant number of fields I could see it, but as is maybe we just make everything a `primary_field`.

**Comment by jpstroop** [comment]
👍

**Comment by tpendragon** [comment]
I moved everything over. The button's still there, but it doesn't do anything. Made https://github.com/projecthydra-labs/hyrax/issues/481 and closing this.
