### ISSUE TITLE
Save button is a little unclear in the file manager

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1032]
I clicked on upload files and selected some. But wasn't sure whether I needed to then click 
Save above or what. Maybe we could look at how these buttons are organized? Maybe do with #852 ?

![screen shot 2017-02-23 at 1 39 40 pm](https://cloud.githubusercontent.com/assets/999701/23273592/9e298008-f9cd-11e6-9bc3-e6a0590f0a78.png)

**Comment by tpendragon** [comment]
@jpstroop Is this a blocker?

**Comment by jpstroop** [comment]
No. #852 will be for images from the archives, so propose doing it then.
