### ISSUE TITLE
"By saving this work I agree to the Deposit Agreement"

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1038]
This text is just above the Save button on Scanned Resources. Doesn't really make sense for us since it's usually going to be a technician or other staff ingesting. Can we just leave it out?

**Comment by jpstroop** [comment]
![screen shot 2017-02-27 at 11 16 21 am](https://cloud.githubusercontent.com/assets/999701/23369094/307d2ea6-fcde-11e6-90db-6006b4c8060a.png)

**Comment by tpendragon** [comment]
We'll want to leave a to do to remove the override when https://github.com/projecthydra-labs/hyrax/issues/435 is closed

**Comment by escowles** [comment]
See https://github.com/projecthydra-labs/hyrax/pull/504

**Comment by escowles** [comment]
Can be rolled into #1049 when projecthydra-labs/hyrax#504 is merged
