### ISSUE TITLE
Refactor Hyrax edit forms to allow easier customization of instructional text

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1039]
This does nothing. Should it collapse the extra fields again? Disappear?

![screen shot 2017-02-27 at 11 19 11 am](https://cloud.githubusercontent.com/assets/999701/23369247/b2110de8-fcde-11e6-8a24-b80b566d6ac8.png)

**Comment by tpendragon** [comment]
Again, we can fix this, but we should remove the override when https://github.com/projecthydra-labs/hyrax/issues/481 is closed

**Comment by jpstroop** [comment]
Gotcha

**Comment by escowles** [comment]
This was fixed by #1050, but I'll keep this ticket around as a placeholder for removing our overrides when Hyrax offers finer-grained customization of the text.
