### ISSUE TITLE
Expose bibrecord JSON-LD combined with local plum record JSON-LD.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1059]
Do we want to cache a fork of the JSON-LD or go to bibdata every time it's requested?

**Comment by escowles** [comment]
I want to see how much of the bibdata JSON-LD we are already storing as properties — in theory it would be nice to be able to simply output Plum's combined properties.  But if that's not viable, then storing the bibdata JSON-LD like we store the MARC seems like a good optimization to avoid having to hit bibdata every time an object is reindexed in Pom.

**Comment by escowles** [comment]
I'm looking back through tickets to see what fields from Plum we want to expose, and have found a couple:
* logo and rights statement #798 
* sort title #758 
* ark (we talked about this yesterday)

Is there anything else?

**Comment by jpstroop** [comment]
Portion Note, navDate?

**Comment by tpendragon** [comment]
Besides those mentioned, we just need the collections it's a member of.

**Comment by tpendragon** [comment]
Also, :+1: to just using plum's properties for the outputted JSON-LD. If we can do it out of solr that's even better, but given the language-tagged fields probably not.

**Comment by escowles** [comment]
The main obstacle I see to using Plum's properties are the handling of `description` and `type` — right now description is suppressed so it doesn't clobber our description (abstract) field, and type (which of course would need to be something else).  We should be able to define fields for these, work around the naming conflicts, and then map them back when we generate the JSON-LD.  But I was starting to think it would be easier to just stash bibdata's JSON-LD and add our values to it...

**Comment by jpstroop** [comment]
> but given the language-tagged fields probably not

yeah, that seems like it wouldn't be possible

**Comment by tpendragon** [comment]
> But I was starting to think it would be easier to just stash bibdata's JSON-LD and add our values to it...

That's probably true. We'd just have to re-grab the attributes for all our objects, but that only takes a few hours yeah?
