### ISSUE TITLE
Menu for adding curation concerns on the home page.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#106]

**Comment by tpendragon** [comment]
Right now it's big and empty, and you have to know where to find the +

**Comment by escowles** [comment]
I think we could either use /classify_concerns/new as the home page, or adapt the view there to list the available curation concerns that can be created and make a more obvious display.

**Comment by jpstroop** [comment]
Hah! I'd never looked at that page, but with some language tweaks and maybe some icons (@axapu ?), I tend to agree--which is to say, can't think of a reason why not.

For our purposes anyway, I think `/classify_concerns` (without a `/{verb}`) should probably redirect to `/classify_concerns/new` as well.
