### ISSUE TITLE
Can't modify users through web UI

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1072]
If I click on a user, I think I'm supposed to be able to change their privledges, or do something?

![screen shot 2017-03-08 at 8 44 42 am](https://cloud.githubusercontent.com/assets/999701/23706298/962ebee6-03db-11e7-8188-a39e3b78ef70.png)

But instead I'm routed to `/` and get this flash:

![screen shot 2017-03-08 at 8 46 46 am](https://cloud.githubusercontent.com/assets/999701/23706358/de1b3bb2-03db-11e7-8410-a61b24f4ed58.png)

**Comment by tpendragon** [comment]
@jpstroop We may want to modify what this ticket is about - I don't think there's any way to get to that `/users` path in the interface. Should we find a way to delete that route?

**Comment by jpstroop** [comment]
That might be a good idea. Does it serve a purpose?
