### ISSUE TITLE
Browse Everything ingest errors if given a path with a space in it

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1095]
```
URI::InvalidURIError: bad URI(is not URI?): file:///opt/rails_app/releases/20170314202335/staged_files/studio/jordan/Nassau Lit/1854/05/00000001.tif
[PROJECT_ROOT]/app/values/file_path.rb:8 :in `clean`
 6 
 7   def clean
 8     ::URI.split(uri).compact.last
 9   end
10 end
```

**Comment by jpstroop** [comment]
We can try to solve this if you want, but images on the Isilion with spaces in their names/paths are an archive-only situation for now, as far as I know.

PUDL and finding aid projects were never allowed spaces in their names, for what amounts to the same reason, and this seems like a reasonable requirement/convention to carry forward.

**Comment by tpendragon** [comment]
I only noticed it because of some paths on the studio share. Easy to fix too

**Comment by jpstroop** [comment]
🆗
