### ISSUE TITLE
Search result list display options

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#1099]
Can we adjust the data which displays in a search result list in Plum?  There is a lot of data displaying now.  I would like to remove some of what is there  (subject, resource type, file format) and I would like to add in the collections the object is associated with and its status.

What I am trying to do now, for example, is find the 41 objects in the Yemeni collection which aren't also in the Islamic manuscript collection.  It would be easier if I could exclude the Islamic collection, but barring that, I could manage if I could see the collections listed.

**Comment by escowles** [comment]
Remove: language, description, date, subjects
Add: bib id, collections
