### ISSUE TITLE
Order Manager should provide feedback while it is processing

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1111]
If a user navigates away from the Order Manager while it is updating, some of their changes may not be saved.  We should provide visual feedback that processing is still happening and/or prevent navigation away while processing is happening.

**Comment by joycebcat** [comment]
So is Safari.  Only some of the files get renamed.  The first few seem to be OK, then it gets spotty and starts skipping and/or stops altogether.

**Comment by joycebcat** [comment]
Ah, nothing prevents a user from clicking on the object's title to return to a different screen, but maybe the renaming isn't complete yet?  There is no sign that the system is still doing anything once the Apply Changes button is clicked.
