### ISSUE TITLE
UTF-8 issues in manifest title.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1122]
https://plum.princeton.edu/concern/scanned_resources/pqv33sw98n/manifest

**Comment by escowles** [comment]
The label displays correctly in my browser and in a text editor — but I see boxes instead of the characters with diacritics in the UV label.  So is this a UV bug?

**Comment by jpstroop** [comment]
Not mine:

![screen shot 2017-04-17 at 9 06 31 am](https://cloud.githubusercontent.com/assets/999701/25089703/3e557ea8-234d-11e7-8411-42cc45f59fd6.png)

Maybe @joycebcat could check the character encoding in the record?

**Comment by escowles** [comment]
Weird — with my JSON viewer extension enabled, the title is fine, but without it, it's broken.  I installed a character encoding extension to see what encodings worked, and none of them did.

**Comment by joycebcat** [comment]
They are coded FE20 and FE21 which is standard.  These diacritics have often posed some problems with display.  There is a newer, preferred encoding for the ligature, but we don't have it in our bib records.

**Comment by jpstroop** [comment]
So does that make it a font issue?

**Comment by tpendragon** [comment]
We need to fix the font in Universal Viewer.
