### ISSUE TITLE
Multi volume work uploader support for browse everything

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1124]
When there's a path with volumes in sub-directories build out volumes for those.

**Comment by jpstroop** [comment]
And I guess the directory name becomes the label for the volume until they change it.

**Comment by tpendragon** [comment]
Any thoughts on how we can accomplish this given the params that are being sent?

```ruby
[2] pry(#<Hyrax::ScannedResourcesController>)> params
=> <ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"3/KdbouD0wnZmDsu10yzNaXYlX7f0KfNs7rNgnSYxvkAI5ZjPAxrde2nEYLvIfik07e0rUxg6G8ywI9A7qmF5A==", "selected_files"=>{"0"=>{"url"=>"file:///Users/tterrell/Projects/plum/staged_files/test/vol1/color.tif", "file_name"=>"color.tif", "file_size"=>"196882"}}, "locale"=>"en", "controller"=>"hyrax/scanned_resources", "action"=>"browse_everything_files", "id"=>"dqz20ss48x"} permitted: false>
```

It doesn't tell you where the root folder selection is (I assume because files can come from multiple directories)

**Comment by jpstroop** [comment]
Can you explain more?

**Comment by jpstroop** [comment]
You can't get what you need from `selected_files[0][url]`?

**Comment by tpendragon** [comment]
@jpstroop My question is more like, given the URL `"file:///Users/tterrell/Projects/plum/staged_files/test/vol1/color.tif"` how do I know when to create a volume vs when I'm just picking six files?

**Comment by jpstroop** [comment]
Are you trying to make the same rake task handle both single and multiple volumes? Seems like if it were a separate rake task, you could rely on `test/vol1/color.tif`

**Comment by tpendragon** [comment]
Rake task? This issue was originally so via the browse everything upload form one could pick a root directory full of directories.

**Comment by jpstroop** [comment]
Oh, right

**Comment by jpstroop** [comment]
It's still one work at a time, though, right?

**Comment by tpendragon** [comment]
This issue is something along the lines of:

`As a digitizer I want to store the files of a MVW in a structure like /bibid/vol1/0001.tif, the select /bibid from the browse everything selector, and have it automatically create volumes for me so that I don't have to manually create many separate volumes when there's few images but many volumes.`

**Comment by escowles** [comment]
Can we use similar logic to IngestService: https://github.com/pulibrary/plum/blob/master/app/services/ingest_service.rb#L26

Or does browse everything just return the list of files, not the directories themselves?

**Comment by tpendragon** [comment]
Re-described in #1239
