### ISSUE TITLE
Fix compressed TIFFs

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1146]
There are currently 69 derivatives jobs failing because Kakadu can't process compressed TIFFs.  It fails with the error:
>The simple TIFF file reader in this demo application can only read uncompressed
TIFF files.  This has nothing to do with Kakadu itself, of course.  If you
would like to read compressed TIFF files, however, it should be sufficient to
re-compile this application with the symbol "KDU_INCLUDE_TIFF" defined, and
link it against the public-domain LIBTIFF library.

We should either replace the TIFFs with uncompressed TIFFs, or recompile Kakadu with better TIFF library support so it can handle compressed TIFFs.  Recompiling probably has licensing issues, but might improve performance.

**Comment by escowles** [comment]
The compressed TIFFs are:

/mnt/diglibdata/hydra_binaries/p0/g3/56/h3/p0g356h32q/00000001.tif
/mnt/diglibdata/hydra_binaries/p1/r6/6m/21/p1r66m2195/00000014.tif
/mnt/diglibdata/hydra_binaries/p2/b8/8s/c7/p2b88sc710/00000218.tif
/mnt/diglibdata/hydra_binaries/p3/48/51/j9/p34851j92f/00000234.tif
/mnt/diglibdata/hydra_binaries/p3/f4/64/69/p3f464690k/00000015.tif
/mnt/diglibdata/hydra_binaries/p4/t6/4j/p4/p4t64jp490/00000013.tif
/mnt/diglibdata/hydra_binaries/p4/x5/1k/n0/p4x51kn03n/00000226.tif
/mnt/diglibdata/hydra_binaries/p5/d8/6r/17/p5d86r174c/00000007.tif
/mnt/diglibdata/hydra_binaries/p5/t3/4v/m2/p5t34vm229/00000009.tif
/mnt/diglibdata/hydra_binaries/p5/x2/1w/h8/p5x21wh83d/00000010.tif
/mnt/diglibdata/hydra_binaries/p6/97/01/37/p69701376q/00000009.tif
/mnt/diglibdata/hydra_binaries/p6/97/01/38/p69701384c/00000016.tif
/mnt/diglibdata/hydra_binaries/p7/65/39/24/p765392450/00000239.tif
/mnt/diglibdata/hydra_binaries/p7/94/09/z9/p79409z940/00000001.tif
/mnt/diglibdata/hydra_binaries/p7/m0/1d/p5/p7m01dp572/00000002.tif
/mnt/diglibdata/hydra_binaries/p7/s7/5g/g5/p7s75gg548/00000002.tif
/mnt/diglibdata/hydra_binaries/p8/33/6k/51/p8336k5119/00000219.tif
/mnt/diglibdata/hydra_binaries/p8/k7/1q/j6/p8k71qj63x/00000006.tif
/mnt/diglibdata/hydra_binaries/p8/w3/2t/74/p8w32t748x/00000004.tif
/mnt/diglibdata/hydra_binaries/p9/s1/63/91/p9s1639117/00000004.tif
/mnt/diglibdata/hydra_binaries/p9/s1/63/91/p9s1639145/00000238.tif
/mnt/diglibdata/hydra_binaries/p9/w0/34/27/p9w034276m/00000006.tif
/mnt/diglibdata/hydra_binaries/pb/85/17/r8/pb8517r82n/00000001.tif
/mnt/diglibdata/hydra_binaries/pb/c3/88/n1/pbc388n16p/00000005.tif
/mnt/diglibdata/hydra_binaries/pd/50/4t/p4/pd504tp46g/00000237.tif
/mnt/diglibdata/hydra_binaries/pd/j5/2z/72/pdj52z722v/00000221.tif
/mnt/diglibdata/hydra_binaries/pf/18/83/n8/pf1883n80k/00000006.tif
/mnt/diglibdata/hydra_binaries/pf/18/83/n8/pf1883n882/00000002.tif
/mnt/diglibdata/hydra_binaries/pf/x7/1c/q0/pfx71cq09n/00000004.tif
/mnt/diglibdata/hydra_binaries/pf/x7/1c/q1/pfx71cq12r/00000230.tif
/mnt/diglibdata/hydra_binaries/pg/15/8d/j9/pg158dj96h/00000002.tif
/mnt/diglibdata/hydra_binaries/pg/h9/3k/22/pgh93k2224/00000011.tif
/mnt/diglibdata/hydra_binaries/ph/41/5r/98/ph415r988j/00000235.tif
/mnt/diglibdata/hydra_binaries/ph/q3/7x/q4/phq37xq41k/00000002.tif
/mnt/diglibdata/hydra_binaries/ph/q3/7x/q5/phq37xq56d/00000002.tif
/mnt/diglibdata/hydra_binaries/pj/d4/74/w8/pjd474w831/00000008.tif
/mnt/diglibdata/hydra_binaries/pj/h3/45/t5/pjh345t584/00000224.tif
/mnt/diglibdata/hydra_binaries/pj/s9/58/h1/pjs958h10t/00000005.tif
/mnt/diglibdata/hydra_binaries/pp/26/78/w7/pp2678w71g/00000227.tif
/mnt/diglibdata/hydra_binaries/pp/v6/3j/09/ppv63j099k/00000000.tif
/mnt/diglibdata/hydra_binaries/pq/23/7k/s8/pq237ks82v/00000002.tif
/mnt/diglibdata/hydra_binaries/pq/z2/0v/s5/pqz20vs57k/00000011.tif
/mnt/diglibdata/hydra_binaries/pr/49/4x/m7/pr494xm78w/00000000.tif
/mnt/diglibdata/hydra_binaries/pr/78/1z/j6/pr781zj60h/00000008.tif
/mnt/diglibdata/hydra_binaries/pr/j4/32/66/prj432668x/00000012.tif
/mnt/diglibdata/hydra_binaries/pr/v0/44/v2/prv044v20w/00000233.tif
/mnt/diglibdata/hydra_binaries/pr/x9/15/s4/prx915s403/00000228.tif
/mnt/diglibdata/hydra_binaries/ps/q8/7d/w3/psq87dw34k/00000225.tif
/mnt/diglibdata/hydra_binaries/ps/t7/4f/r7/pst74fr766/00000232.tif
/mnt/diglibdata/hydra_binaries/pt/43/5j/g0/pt435jg06k/00000236.tif
/mnt/diglibdata/hydra_binaries/pt/m7/0p/w4/ptm70pw410/00000240.tif
/mnt/diglibdata/hydra_binaries/pt/t4/4r/p2/ptt44rp22m/00000222.tif
/mnt/diglibdata/hydra_binaries/pv/h5/3z/z1/pvh53zz19s/00000002.tif
/mnt/diglibdata/hydra_binaries/pv/m4/10/t8/pvm410t819/00000002.tif
/mnt/diglibdata/hydra_binaries/pv/m4/10/v1/pvm410v109/00000217.tif
/mnt/diglibdata/hydra_binaries/pv/q2/81/p4/pvq281p467/00000001.tif
/mnt/diglibdata/hydra_binaries/pw/08/94/c1/pw0894c10w/00000003.tif
/mnt/diglibdata/hydra_binaries/pw/66/36/55/pw6636555t/00000007.tif
/mnt/diglibdata/hydra_binaries/pw/95/07/18/pw9507185j/00000003.tif
/mnt/diglibdata/hydra_binaries/pw/95/07/20/pw95072076/00000010.tif
/mnt/diglibdata/hydra_binaries/px/g9/4k/s5/pxg94ks567/00000231.tif
/mnt/diglibdata/hydra_binaries/pz/60/3s/z4/pz603sz48v/00000003.tif
/mnt/diglibdata/hydra_binaries/pz/60/3s/z5/pz603sz57t/00000223.tif
/mnt/diglibdata/hydra_binaries/pz/89/0t/x0/pz890tx005/00000004.tif
/mnt/diglibdata/hydra_binaries/pz/89/0t/x0/pz890tx07b/00000220.tif
/mnt/diglibdata/hydra_binaries/pz/g6/4w/p2/pzg64wp27h/00000229.tif
/mnt/diglibdata/hydra_binaries/pz/k5/1x/h2/pzk51xh219/00000001.tif
/mnt/diglibdata/hydra_binaries/pz/w1/31/65/pzw131659s/00000003.tif

**Comment by jpstroop** [comment]
Are these PUDL or PULFA images? If PUDL, @roelmoon would probably like to know.

**Comment by escowles** [comment]
The images in MC016 that couldn't be processed by Kakadu are a little more complicated than i thought.  I thought there were whole objects where all of the page images were compressed.  But now that most of MC016 is ingested, there are 235 images.  Some of the are compressed, but some are 256-color instead of grayscale.  And some objects have issues with all of their files, but some are just one file in an otherwise OK object.

I think we can still update the files (save the current versions in another location, and convert them to grayscale for ingest).  But do we want to review these at all?  Is this just sloppy digitization?

**Comment by jpstroop** [comment]
It was a Crowley project, so sloppiness is almost certainly the case. Were
any of the 256 color images actually color?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by rmoon** [comment]
I can run a batch routine to normalize the files. It would be ideal if the component IDs can be isolated.

I agree, Crowley hasn't generated much confidence lately.

**Comment by escowles** [comment]
@rmoon: When the MC016 ingest has completely finished, I'll make a complete list of the affected component IDs and files.  I haven't downloaded any of the TIFFs to see if they are actually color, or if there are any other issues with them.  But taking a quick look at some of them seems like a good idea to make sure there aren't bigger problems here.

**Comment by escowles** [comment]
@rmoon: the ingest jobs have finished and there are 238 files that fail to generate derivatives 
[files.txt](https://github.com/pulibrary/plum/files/910104/files.txt)

I downloaded 10 files at random, and all 26 of the files that are 256-color, and they were all grayscale.  Of the 256-color images, most were text, but some also had photos/illustrations, and a few were handwritten "Please omit" notes.

**Comment by tpendragon** [comment]
@rmoon Any status update on normalizing the files?

**Comment by rmoon** [comment]
Done. fixed images merged with rest of MC016.

**Comment by escowles** [comment]
Thanks @rmoon — I'll reingest the impacted objects once the pudl0003 ingest has finished.
