### ISSUE TITLE
Update ARKs to point to OrangeLight

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1151]

**Comment by escowles** [comment]
If a completed record has a source_metadata_identifier, and it's a Bibdata identifier, then the ARK should be updated to point to "https://pulsearch.princeton.edu/catalog/#{source_metadata_identifier}#view".

But what about items without a source_metadata_identifier, or a PULFA identifier?

**Comment by jpstroop** [comment]
For PULFA, I'd say point to the component page in findingaids.princeton.edu. For items without a source_metadata_identifier maybe we need to point into Plum??

**Comment by tpendragon** [comment]
:+1: to pointing into Plum. Or we just don't mint those ARKs yet - right now if that happens those are test items, yeah?

**Comment by escowles** [comment]
I guess I'm not sure what items would be complete without remote metadata.  We've talked about graphic arts or other projects that would author objects in Plum from scratch, and those seem like they should be given ARKs (which maybe point to DPUL?).  But do we expect any objects right now that wouldn't have remote metadata?

**Comment by jpstroop** [comment]
> I guess I'm not sure what items would be complete without remote metadata.

There's actually a potential project looming right now with a large set of Geniza fragments from different libraries, where the only descriptive metadata we'd have is the shelf number from the library holding the original. If it goes forward, we'd probably just stash that in Plum's title field and call it good, I'd think.
