### ISSUE TITLE
Remove partial overrides for "Content License"

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#119]
There are some [form overrides related to getting Access and Use statements teased apart](https://github.com/pulibrary/plum/blob/master/app/views/curation_concerns/scanned_resources/_form_access_policy.erb),  and I'm not sure how or why or when those were originally applied; they may be cruft from some of the WorthWhile code that Matt ported over.

In any case, it looks like a [`RightsService` that uses QA has since been introduced](https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/curation_concerns/base/_form_rights.html.erb), and maybe we can take advantage of that. Ideally we'd be able to have a YAML file that stores labels and text for each policy, e.g.:

```yaml
---
- :label: General (Open)
  :text: Princeton University Library ....
- :label: Public Policy Papers (Open)
  :text: The collection is open ....
```

And that's basically what QA does, no?

This seems related to #101 and #74.

**Comment by jpstroop** [comment]
I guess this is the way: https://github.com/pulibrary/plum/blob/master/config/authorities/rights.yml, though our rights policies won't have URIs.

Any thoughts about this @tpendragon or @escowles

**Comment by tpendragon** [comment]
Yeah, I think that's the established way.

Our rights policies -could- have URIs, it wouldn't be that tough to embed some RDF-A.

**Comment by tpendragon** [comment]
As for the text, I don't think there's a clear way to get it out right now. I'll have to dig deeper.

**Comment by jpstroop** [comment]
I was thinking about this on my way home, and, actually, nearly all of the
statements we'll need to support are likely to be cribbed from web pages.
So I guess we could start by using those URIs and see how far we get.

I will look into this more tomorrow.

**Comment by escowles** [comment]
I bet a lot of the rights statements map to CC, Europeana or RightsStatements.org.  For anything that doesn't, it would be interesting to see if there's any commonality with OregonDigital and UCSD.

If QA doesn't handle the text, then we could always put it in the yaml file and parse it ourselves.  We could also use that as a narrowly-scoped linked data caching project...

**Comment by jpstroop** [comment]
At least going from my experience w/ the PUDL several years back, it's not really about what the rules map to (it's CC-BY in almost all cases, as far as I can tell), but the librarians wanting their specific wordsmithing and policies to be visible or linked. E.g.:

* RBSC: http://rbsc.princeton.edu/services/rights-permissions
* East Asian: https://library.princeton.edu/libraries/eastasianlib/rights
* General Digitization: "Princeton University Library makes no claims to rights over these images. They are presented for free, on a non-commercial, open-access basis, for fair-use academic and research purposes only. Anyone who claims copyright over any part of these resources and feels that they should not be presented in this manner is invited to contact Princeton University Library, who will in turn consider such concerns and make every effort to respond appropriately."

**Comment by escowles** [comment]
Following the Hydra metadata group [rights recommendation](https://wiki.duraspace.org/display/hydra/Rights+Metadata+Recommendation) that would boil down to:

```
edm:rights = <CC-BY>
dc:rights = <boilerplate/link/etc.>
```

And if the boilerplate/link/etc. varies mostly by which department is managing the materials, then maybe it's more of an AdminSet issue than a rights issue per se?

**Comment by jpstroop** [comment]
That seems like a good approach, though in some ways it feels premature to be trying to figure this out--it will be an easier conversation to have w/ the stakeholders when we can demonstrate the implications.

I can see two approaches:

1.  Use what we get for free until the use cases are clearer. Despite my concerns about the persistence of local URIs, get rid of the overrides and plug 

    * RBSC / http://rbsc.princeton.edu/services/rights-permissions
    * East Asian / https://library.princeton.edu/libraries/eastasianlib/rights

    into QA for now. 

2. Go ahead and implement the rights metadata group's recommendation, either in Plum or CurationConcerns.That approach maps reasonably cleanly to IIIF's [`license` and 'attribution`](http://prezi-21.iiif.io/api/presentation/2.1/#rights-and-licensing-properties), thought the [predicates are a little off](http://iiif.io/api/presentation/2/context.json), which will be good for the long haul.

**Comment by escowles** [comment]
Using QA for now and waiting for a better understanding of how it should work sounds good.  I think it would be great to implement the rights recommendation in CurationConcerns, but having a clear understanding of how it should work will make it a lot easier to get that right.

**Comment by jpstroop** [comment]
:+1: 

Just to log it somewhere, the Hydra [Minimal Rights Metadata](https://wiki.duraspace.org/display/hydra/Rights+Metadata+Recommendation#RightsMetadataRecommendation-MinimalRightsMetadata) recommendation does seem a little IR-centric, i.e., compare what it recommends with the text above:

> Princeton University Library makes no claims to rights over these images. They are presented for free, on a non-commercial, open-access basis, for fair-use academic and research purposes only. [...]

`_:thing dct:rightsHolder "not us" .`

For our case I think `edm:rights` for a URI and `dc:rights` (as @escowles recommends) or `dct:license` ('A legal document giving official permission to do something with the resource.') might make more sense.
