### ISSUE TITLE
Typos/errors in METS files

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1190]
One file has an old form of the bib record URL:
* pudl0127/4746986.mets:	http://catalog.princeton.edu/cgi-bin/Pwetrecon.cgi?BBID4746986

Two files have typos in some filenames (see [google doc](https://docs.google.com/spreadsheets/d/10rPi33nSDtVBmzwJ8VsgnOy0o2UWbMPSluBC-yVBH9Q/edit#gid=0) for full list):
* pudl0003/tb137_3513.mets
* pudl0003/tc83_3067.mets

**Comment by jpstroop** [comment]
At least I think that's the case, or maybe the URL wasn't changed properly because it's missing the "="?

**Comment by escowles** [comment]
I get the error `The requested URL /cgi-bin/Pwetrecon.cgi was not found on this server.` with or without the `=`.

**Comment by jpstroop** [comment]
Another typo:`Pwetrecon` should be `Webrecon`
