### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1191]
pudl0003/td73_3870.mets contains references to files that don't exist:

* /mnt/diglibdata/pudl/pudl0003/td73_3870/vol12/00000026.tif
* /mnt/diglibdata/pudl/pudl0003/td73_3870/vol12/00000027.tif
* /mnt/diglibdata/pudl/pudl0003/td73_3870/vol12/00000028.tif

The directory contains 00000001.tif - 00000025.tif

**Comment by jpstroop** [comment]
@roelmoon or @joycebcat, do these ring a bell with you?

**Comment by rmoon** [comment]
Tom Ventimiglia can confirm, but I believe the issue was that the volumes were stored in their enclosures out of order. Vols 12-13 needed to be switched, so the dir names were changed. Vol 13 has 28 image files.

**Comment by escowles** [comment]
Tom confirmed that the three missing files in vol12 could simply be deleted.  I've updated the METS file and the ingest was successful: https://plum.princeton.edu/concern/multi_volume_works/pww72fc20c
