### ISSUE TITLE
Support (authorized) 3rd-party uploads for LAE

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1194]
MOUs, etc. aside, support auth via non-Princeton creds.

**Comment by escowles** [comment]
Do we have any idea what would be the best auth mechanism?  I assume there isn't a shared project site like Cicognara's Basecamp that would cover everybody.  So I don't know if Google or some other popular OAuth provider would be good enough.  Or whether we should consider adding an internal user-management mechanism or even get NetIDs for external users (which could make sense if it's a small number of external users).

**Comment by jpstroop** [comment]
I think Google would be good enough, but I'm also happy to wait until a real use case surfaces. Let's just keep it in mind.
