### ISSUE TITLE
Issues with vocabulary migrations

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1200]
Unable to deploy current set of vocabulary migrations: 
- `20170418134613_drop_vocabulary_collections_table.rb`
- `20170418135208_remove_vocabulary_collection_from_vocabulary_terms.rb`
- `20170418135317_add_parent_to_vocabularies.rb`

This is the error:
```
PG::DependentObjectsStillExist: ERROR:  cannot drop table vocabulary_collections because other objects depend on it
DETAIL:  constraint fk_rails_e34fbb6276 on table vocabulary_terms depends on table vocabulary_collections
```

Swapping the positions of the drop and remove migrations seems to solve that issue. If you do that manually, the last migration raises this error:
```
PG::UndefinedTable: ERROR:  relation "parents" does not exist
```

**Comment by escowles** [comment]
@eliotjordan Where are you starting from? I just tried the following to migrate from immediately before those three migrations, and it worked without errors:

```sh
git clone git@github.com:pulibrary/plum.git
cd plum
git checkout becea5629781d0b6d68e37285983b25ecf586fdc
bundle install
bundle exec rake db:migrate
bundle exec rails g active_fedora:noid:seed
bundle exec rake hyrax:workflow:load
# bundle exec rake hyrax:default_admin_set:create # skip for now (needs fedora to be running)
git checkout master
bundle exec rake db:migrate
```

**Comment by eliotjordan** [comment]
This happened when deploying to hydra-dev, but seems to work fine on my local machine. So maybe it's an issue with Postgres? This happened with a branch I had rebased against master, but I bet it will happen with master as well. 

Heaven output: https://gist.github.com/tpendragon/0edf7c121e0fdc25ffc97e925808eb16#file-stderr-L8-L17

**Comment by escowles** [comment]
That makes sense — it worked fine for me to do it in the wrong order locally because I'm using SQLite which doesn't enforce integrity, but then it failed with Postgres.  I'll setup Postgres locally and debug.
