### ISSUE TITLE
Edit button on Home screen

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#1246]
When Tom V. is working in DPUL, clicking on the "edit' button on the Home screen always gives him an error.  I suggested he try some different browsers but this doesn't make a difference.  He has used the Mac Firefox version, and also Firefox 53.0 on Windows.

**Comment by tpendragon** [comment]
Looks like it's only an issue with the east asian collection. Backtrace: https://app.honeybadger.io/projects/51733/faults/33461705#notice-summary
