### ISSUE TITLE
Auto-populate sort title

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1253]
Look at feature in current LAE app--does it use language or is it just a canned list of articles?

**Comment by escowles** [comment]
This is language-dependent and configured in the current LAE app here: https://github.com/pulibrary/pul-store/blob/development/config/pul_store.yml.tmpl#L8-L28

**Comment by escowles** [comment]
Since language is a multi-select right now, how do we tell which is the title language?  Do we just use the first one?

**Comment by tpendragon** [comment]
Where "first" is ever changing. I guess thats the best we can do.

**Comment by jpstroop** [comment]
I think the current app uses dc:title for the first title, and
dc:alternative for the rest. That should solve one part of this. I'd say go
with the first language entered for the other.

-Js

Sent via mobile. Please excuse typos, brevity, etc.


On May 8, 2017 3:20 PM, "Trey Pendragon" <notifications@github.com> wrote:

Where "first" is ever changing. I guess thats the best we can do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pulibrary/plum/issues/1253#issuecomment-299964234>, or mute
the thread
