### ISSUE TITLE
UI for linking fields to vocabs

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1255]
Maybe each model could define the fields that could be controlled vocab fields, e.g. `self.controlled_fields = [:genre, :language, :subject]`

Then we could have an AR model that let you pick a Vocab and link it to a field like `EphemeraFolder.genre`.  There would need to be a helper to interrogate all of the CurationConcerns to see which ones had controllable fields for generating the forms.  But once those records were created, AuthorityFinder could use that data to select for forms, etc.

I'm not sure how this fits in with templates and having different profiles/templates/whatever for LAE vs. South Asian Ephemera, though.  Maybe the template could be a container for the Vocab/field mappings?

**Comment by tpendragon** [comment]
I think we might have to adjust the way we store controlled fields to actually reference the vocabulary it's a part of, so that there isn't ID collision between vocabs. Then we should be able to, in the template, just assign each field a vocab.

**Comment by tpendragon** [comment]
Oh! This was actually a problem in OD I forgot about. If controlled vocabs are chosen as part of the template, it means you have to keep track of which template the object was ingested as part of, and never delete the template.

**Comment by escowles** [comment]
I believe the Term ids are globally unique (that is, they aren't a sub-resource of Vocabularies), so there shouldn't be collisions.  So I don't think we have to keep the templates forever to know which terms a record is linking to.

But we would need to know which template to use for displaying the form — which seems to be related to the collection an item is in, more than the object itself.  Do we need to model the different ephemera collections as something more than a Collection, in order to have a place to keep track of the vocab-field mappings?

**Comment by escowles** [comment]
I'm trying to work out the relationships here, so I put together an E-R diagram:

https://docs.google.com/drawings/d/1ENE1GCEoHnhjg3oO_cDUJdwdN0dHhCBzqP-Q7vHrv1E/edit
