### ISSUE TITLE
Make report of scanned maps with missing bounding boxes

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1263]
- Maps without boundings boxes and that do not have FGDC metadata to pull from
- List of bibids should be divided by holding location (Lewis map collection and RBSC historic maps)

**Comment by eliotjordan** [comment]
@tampakis List of all ImageWorks without bounding boxes and with no FGDC record:
[image_works_no_coverage.csv.zip](https://github.com/pulibrary/plum/files/987879/image_works_no_coverage.csv.zip)

**Comment by tampakis** [comment]
[bib_ids_no_coverage.zip](https://github.com/pulibrary/plum/files/1008305/bib_ids_no_coverage.zip)
