### ISSUE TITLE
Make report of scanned maps without ARK in MARC record

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1265]
- Scanned maps that are publicly viewable should have ARKs inserted into the 856 field in MARC.
- Make a list of records that do not so they can be corrected.
- List of bibids should be divided by holding location (Lewis map collection and RBSC historic maps)

**Comment by tampakis** [comment]
Decision - wait until maps are ingested before updating Bib records (for eventual display in Orangelight)

**Comment by eliotjordan** [comment]
ARKs inserted into 856 fields for all completed ImageWork and MapSet records. Thanks to @mzelesky for the heavy lifting.
