### ISSUE TITLE
object appears as private and complete, but isn't marked as private or complete

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#1271]
This item appears in DPUL, marked as private, despite all volumes and the overall object being marked as open, and all volumes and the overall object being marked with Takedown.
https://dpul.princeton.edu/marquand/catalog/vt150j33m

**Comment by tpendragon** [comment]
I don't think this is a bug, maybe just a vocabulary problem. In DPUL when that checkbox for "public" is un-ticked, it means people can't discover/access it if they're not an admin. So what happens is when an item is "taken down" in Plum, it makes it un-public in DPUL. That way any custom curator fields/modification aren't deleted, but the public won't have access to it until it's not taken down anymore.

**Comment by tpendragon** [comment]
@joycebcat Can we close this?
