### ISSUE TITLE
Deleting geo work files raises error in cleanup_derivatives method

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1277]
`undefined local variable or method logger'`

[Offending line.](https://github.com/pulibrary/plum/blob/master/app/services/scanned_map_derivatives_service.rb#L16)

I'm guessing we just need to define a logger, or use `Rails.logger.debug`

**Comment by eliotjordan** [comment]
Confirmed that this is an issue in [plum_derivatives](https://github.com/pulibrary/plum/blob/2a96ea5464d617ea2ef74699f5a90e4a9022988f/app/services/plum_derivatives_service.rb#L26). I presume it will be an issue in all the locations in #1251 where `logger.debug` is called. 

@escowles Does this happen on your development instance?

**Comment by escowles** [comment]
@eliotjordan Yes, I'm seeing it in my local env now that I'm deleting objects in the UI — I didn't see it when I was using a rake task to delete items.  Using `Rails.logger` in all of those places where a logger wasn't defined seems like the right thing to do.
