### ISSUE TITLE
One-step workflow for LAE Folders

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1283]
Folders should only have one step: Make Public, or something similar. ("Complete"?). However, all this does is make the metadata record public. The images should be hidden until a second QA process happens. How do we want to do that?

**Comment by escowles** [comment]
I think this sounds like a three-state workflow:
* pending
* new state (discoverable?): public metadata but restricted images
* complete

**Comment by tpendragon** [comment]
I wonder if "Pending" is useful?

**Comment by escowles** [comment]
We talked around that quite a bit, and I think everybody was fine with skipping the Pending state, and just starting with Discoverable.
