### ISSUE TITLE
Linking to manifest from UV in the OL produces an error

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#1292]
Redirects (I think) to here:

https://plum.princeton.edu/concern/scanned_resources/pjd474c77c/manifest?locale=en?manifest=https://plum.princeton.edu/concern/scanned_resources/pjd474c77c/manifest?locale=en

**Comment by tpendragon** [comment]
Backtrace: https://app.honeybadger.io/projects/51732/faults/33298891#notice-summary
