### ISSUE TITLE
If I upload multiple pages and my connection dies, what happens

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#131]

**Comment by tpendragon** [comment]
If you kill your internet connection in the middle, any that were sending will fail. Any that haven't started will wait for a connection. When you're done, you end up with as many pages that finished having uploaded - and they're not in order of upload, but rather in order of which managed to make it in time.

**Comment by tpendragon** [comment]
Browse Everything is sort of billed as the solution to this, assuming we don't want to figure out chunked uploads. Would that be something we want in Curation Concerns?

**Comment by escowles** [comment]
:+1: to adding Browse Everything support to Curation Concerns -- it seems like a better, shareable way to address this kind of problem.

**Comment by escowles** [comment]
Closing because Browse Everything support was added in #171
