### ISSUE TITLE
Ingest Additional Derrida Items

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1316]
We have ingested the Derrida items that we have METS files for:

RBD1/c8933
RBD1/c8959
RBD1/c8971
RBD1/c9157
RBD1/c9159
RBD1/c9166
RBD1/c9167
RBD1/c9168
RBD1/c9179
RBD1/c9626
RBD1/c9654
RBD1/c9661
RBD1/c9670
RBD1/c9758
RBD1/c10088
RBD1/c10091
RBD1/c10099
RBD1/c10310
RBD1/c10433
RBD1/c10447
RBD1/c10452
RBD1/c10455
RBD1/c10456
RBD1/c10922
RBD1/c10923
RBD1/c12860
RBD1/c12869
RBD1/c13073
RBD1/c13076
RBD1/c13182
RBD1/c13199
RBD1/c13201
RBD1/c13228

There are an additional 30-40 items that have been digitized but not ingested, and no METS files will be created for these.

**Comment by escowles** [comment]
@rlskoeser @rmoon I've created this ticket to track ingesting the remaining Derrida items — we decided that they should be ingested by the digitization techs using Plum.

**Comment by rlskoeser** [comment]
Thanks!
