### ISSUE TITLE
Variant titles (246) from Voyager missing

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#1330]
Le fontane di Roma nelle piazze e lvoghi ...
This title has a 246 (variant title) with the spelling modernized (luoghi), but this doesn't appear in DPUL and can't be searched for.  246 isn't the only place to find other titles; I haven't done a comprehensive check on this.

**Comment by tpendragon** [comment]
Sure enough, looks like DC.alternative isn't coming over from bibdata.

**Comment by tpendragon** [comment]
Ah, @tampakis fixed this a couple months ago: https://github.com/pulibrary/marc_liberation/pull/230/files. I had to edit the record, click the checkbox to refresh the metadata, and hit save, and it came right over. We may have to re-fetch metadata for everything.
