### ISSUE TITLE
Scroll bars on flip cards

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#1331]
I got Don S. to cut down his text for the reverse of the flip cards.  I would like to require that flip card text be limited to ~50 words so as not to require scrolling.  With this proviso in place, is it possible to remove the scroll bars?  They seem to always appear regardless of the text length and the cards would look cleaner without them.

**Comment by tpendragon** [comment]
Yes! Those scroll bars look awful.

**Comment by tpendragon** [comment]
Migrated to https://github.com/pulibrary/pomegranate/issues/276
