### ISSUE TITLE
LAE Linked Data

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1332]
Make sure the controlled vocabulary terms show up in Turtle/JSON view as dereferencable URIs

**Comment by tpendragon** [comment]
Is this only descriptive metadata? Getting the structural metadata to de-reference would be...harder.

**Comment by escowles** [comment]
Yes, I assume we're talking about the descriptive metadata on the EphemeraFolders, not trying to expose the Box/Folder hierarchy.

**Comment by jpstroop** [comment]
Yes, definitely not structural metadata, though we could expose the Manifest via the RDF...EDM has a pattern for doing that but I forget what it is.

The public site currently has, e.g., http://lae.princeton.edu/catalog/07q1s.ttl

but there's no real way to crawl the site--there are URIs for the controlled vocabs, but items never reference other items, for example. How to we expose the entire LAE graph?

**Comment by tpendragon** [comment]
We can just provide a TTL serialization for the collection.
