### ISSUE TITLE
Mechanism for pre-caching IIIF manifests

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1348]
We will probably want a job/task to pre-cache IIIF manifests. There are thousands of MapSets with manifests that take from 30 seconds to minutes to load. This isn't a good user experience when a manifest is viewed for the first time in Orangelight or GeoBlacklight.

**Comment by tpendragon** [comment]
No (on purpose - so that changes to manifest stuff actually happen)

**Comment by escowles** [comment]
So, if the manifests for the MapSets are too slow, should we warm the cache for them as part of the deploy?

**Comment by tpendragon** [comment]
Probably. Might want to time how long that takes though.
