### ISSUE TITLE
Include source metadata identifier in seeAlso metadata referenced by item manifests

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/plum#1372]
Source metadata identifier would be valuable to include in the machine readable metadata.

Particular need for me is to be able to match up digitized Derrida materials with the existing records in our system.

**Comment by escowles** [comment]
We have another ticket (1306) for including a link to the MARC in Bibdata (e.g., https://bibdata.princeton.edu/bibliographic/1234567) — would that be a reasonable way to include the source metadata identifier?

**Comment by rlskoeser** [comment]
Accessing it MARC wouldn't be my first choice, but would be acceptable and I can see how that could make sense for the application.

Are there MARC records for items from the finding aids?

**Comment by escowles** [comment]
@rlskoeser I was mostly thinking that we could include a seeAlso link that included the identifier in the URI (not that you would necessarily want to fetch the URI, though of course you could).

The finding aids would link to the EAD, e.g., https://findingaids.princeton.edu/collections/RBD1.1/c284.xml

**Comment by rlskoeser** [comment]
@escowles oh, I see. That sounds great.  That would be great for what I'm doing, because I'll be matching up with records in our system based on those URIs.
