### ISSUE TITLE
An ingester should be able to assign a label to represent a book and not have it overidden by Voyager

### ISSUE THREAD

**Issue by terrellt** [pulibrary/plum#14]

**Comment by jpstroop** [comment]
The only use case I can think of for persisting this permanently, as opposed to overriding it w/ the title from Voyager when the bib data is imported, is when the label contains information regarding the completeness or extent of the set of images, e.g. "volume 7" or "plates 4-6".

Are there other use cases? (pinging @joycebcat @roelmoon)

If these are the two use cases, then I think we should consider two properties. One for a temporary title (which can just be dc:title which _will_eventually overridden) and something else (maybe `dct:extent`, except that we're already likely to map that to MARC 300?) about the content or completeness, which is intended to persist.

**Comment by flyingzumwalt** [comment]
For now. This is covered by the portion_note.

**Comment by joycebcat** [comment]
I don't think we need to keep the temp label once there is a V record (if there will be a V record).  You suggest that dc:title _will_ eventually be overridden.  Starting with brittle books this will be the case, but down the road there might well be book material without a V record (potentially some Derrida material)

dc:extent is NOT the right place to indicate "volume 7" or things like that which indicate a part of the overall resource.

**Comment by terrellt** [comment]
@joycebcat dc:title will be overridden as soon as there's a record - if there never is one, then it won't be (for this project there will be, yes?)

Do you have a better predicate for part notes?
