### ISSUE TITLE
Add Rights Statement and Physical Number to Ephemera JSON-LD

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#1408]
@jpstroop Do we want plum's rights boilerplate to show up in LAE? Or always index the LAE statement that exists?

**Comment by jpstroop** [comment]
AFAIK there's the existing LAE boilerplate that we should use, and I wonder if we should default to http://rightsstatements.org/page/InC-EDU/1.0/ as well? Might be a question for stakeholders the next time we meet.
