### ISSUE TITLE
Can't edit structure

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1425]
Mark Armstrong reported that edits to the structure of "Villa Borghese fuori di Porta Pinciana" (https://plum.princeton.edu/concern/scanned_resources/pgh93kc09x) are not saved.  There are no errors, but the edits are not reflected in the viewer, or in the structure editor after reloading.  I can confirm seeing the same behavior, and no obvious errors in the logs.

**Comment by escowles** [comment]
Updating the title to reflect the fact that this looks like all objects, not just the particular one that Mark reported initially.

Also, I noticed in debugging that it looks like there are two POSTs being sent to save_structure, not one as I would expect.

**Comment by tpendragon** [comment]
I wonder if this is a problem with updating those blank nodes. I think for the Pumpkin work they added some code to delete the node and recreate it on save?
