### ISSUE TITLE
ImageWork and MapSet manifests are not accessible to anonymous users

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1434]

**Comment by tpendragon** [comment]
This might be a side effect of the new `:manifest` permission in CanCan we added for LAE?

**Comment by eliotjordan** [comment]
I think so. I have a branch that I'm working on to fix this.  :crossed_fingers:

**Comment by escowles** [comment]
Yes, I feel like the permissions things have gotten worse recently — and I hope that https://github.com/pulibrary/plum/pull/1430 is moving things in the right direction.  Anonymous users should be able to `:manifest` public curation_concerns, but maybe we need to be explicit about that now.
