### ISSUE TITLE
LAE identifiers

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1436]
How do we want to migrate the LAE identifiers?

1. Put them in a `local_identifier` field so we can map them to the old IDs?
1. Use them as the primary identifiers instead of minting new NOIDs?  Since they are 5 characters, they won't conflict with Plum's identifiers.
1. Something else?

**Comment by jpstroop** [comment]
> Use them as the primary identifiers instead of minting new NOIDs? Since they are 5 characters, they won't conflict with Plum's identifiers.

I like this one, if it's not going to cause a hassle at a later date for some reason.
