### ISSUE TITLE
Derrida items without previews

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#1448]
Finished:
--Collective, L’écriture et la psychologie des peuples
Error URL: https://plum.princeton.edu/concern/file_sets/pmw22xv75b

--Lévi-Strauss, Tristes tropiques
Error URL: https://plum.princeton.edu/concern/file_sets/pkp78jp05z
 
Not yet completed:
--Leibniz, Nouveaux Essais sur l’entendement humain
Error URL: https://plum.princeton.edu/concern/file_sets/p8w32td21d
--Levinas, Difficile Liberté
Error URL: https://plum.princeton.edu/concern/file_sets/p02873m553
-- Derrida/Husserl, Origines de la géométrie
Error URL: https://plum.princeton.edu/concern/file_sets/pgf06jr51b

**Comment by escowles** [comment]
@rlskoeser I checked these items, and all of these pages are showing up fine in the viewer on the ScannedResource.  The FileSet show page says "No preview available", but I think that is broken for all FileSets.  I've opened #1451 to fix that.

**Comment by rlskoeser** [comment]
@escowles #1451 has been closed but I just heard from Elise that she still can't view the preview images, which means she can't do the work she needs to do to label the pages.

Here is the screenshot she sent me with her comment:
>  I've attached a screenshot of what it looks like when I attempt to click the individual pages.
![screen shot 2017-09-04 at 12 24 44 am](https://user-images.githubusercontent.com/691231/30065197-143dcda2-9222-11e7-9d15-f024f28414a6.png)

**Comment by escowles** [comment]
@rlskoeser I've created a new ticket for the OSD viewer not showing up: #1472   — previously, I thought there was a data or permissions issue, but this seems like the OSD viewer is not working for any objects at all.
