### ISSUE TITLE
Who should be notified that records are ready for review?

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#153]
* A mailing list?
* Several users personal email addresses?
* All users who have the `reviewer` role?
* Some other option?

**Comment by escowles** [comment]
In the state diagram in #211, the following states trigger notification:
* final_review
* complete
* flagged (aka needs attention)
* takedown

**Comment by escowles** [comment]
I think the more pressing question before tackling local mail delivery in #201 is: who wants to get an email when a record is completed in staging?  @joycebcat? @jpstroop? @tpendragon?  Maybe we should setup a dummy account for this, so we can check to see if it actually works, without having to sign up to actually get these emails in our real accounts?

**Comment by jpstroop** [comment]
I think the question is slightly broader: who gets an email at which point(s) in the workflow, right?

![](https://cloud.githubusercontent.com/assets/856924/11530241/08d1eff4-98c1-11e5-9610-42e1a22152f5.jpg)

**Comment by escowles** [comment]
@jpstroop Yes, you're right that we have several points in the workflow where we want to send notifications.  At some point, we will also need to resolve the question of how different environments behave.

My thinking of how to approach #201 was:

1. Enable sendmail on hydra-dev so we can send mail (this is done already, and worked for both my princeton and personal email addresses).
1. Update plum to sendmail for sending mail, and use an email address that we don't mind dumping a bunch of messages on.

Once that's done, this issue (#153) would be a good vehicle for deciding on a more flexible system for deciding who gets notified (either a mailing list or using plum's roles).  E.g., we could make roles for each workflow state (`notify_pending`, `notify_metadata_review`, etc.) and we could email all users in the appropriate role.

**Comment by jpstroop** [comment]
@kevinreiss do you know the process for getting a dummy email address?

**Comment by escowles** [comment]
I thought it would be easier to setup a dummy email address than figure out a long-term approach.  But how about:

* Creating a role for each workflow state, and notifying every user with that role when a record enters that state.

This will be very flexible, and allow admin users to manage notifications.  My understanding is that it's mostly admin users who want to be notified.

**Comment by jpstroop** [comment]
Sort of related to #210

**Comment by joycebcat** [comment]
It is mostly admin users who want to be notified except for the use case of notifying the project initiator at the "final review" and "complete" stages.

**Comment by jpstroop** [comment]
Unless the developers are admins...which maybe we don't need to be for the production system.
