### ISSUE TITLE
Ingest files from browse everything with checksums

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#178]
Stops partial file downloads from applying.

**Comment by jpstroop** [comment]
:+1:

**Comment by escowles** [comment]
Should this be implemented in ActiveFedora?  It seems like a generally-applicable issue that all uploads to F4 need to have checksums specified to prevent applying partial uploads.

**Comment by tpendragon** [comment]
I'm not sure. Running checksums could take a fair bit of time, doing it before ingest would make it take even longer.

**Comment by escowles** [comment]
I'm sure some people wouldn't want it turned on by default because the performance penalty.  But the functionality could be in AF, with a way of triggering it from the application.  Not sure about the mechanism -- globally enable in an initializer? enable on individual objects?

**Comment by jpstroop** [comment]
Still an issue?

**Comment by escowles** [comment]
We're not loading the files into Fedora, so I don't think this applies any more.
