### ISSUE TITLE
Structural metadata for books.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#18]

**Comment by tpendragon** [comment]
@jpstroop @escowles @eliotjordan I'm thinking that the reorder interface and the structural metadata interface have to be in the same place. Otherwise what happens to the logical order (with intermediate nodes like "Chapter 1") when you re-order page 3 away from page 4?

**Comment by jpstroop** [comment]
Ugh, good point. Although I suppose a structure (range) could order the pages differently. Can't say that's a use case that's come up though.

**Comment by jpstroop** [comment]
There will also be cases where a page needs to be repeated in the structure because, e.g., chapter 1 ends and chapter 2 begins on it.

**Comment by jpstroop** [comment]
This leads me to think that the order within a structure and the order of the sequence should be independent. It makes sense to use the sequence/order as a point of departure, but maybe that's all.

**Comment by jpstroop** [comment]
oops. typing w/ thumbs...

**Comment by tpendragon** [comment]
I can't really think of a way to model order of structure/sequence separately, or what that gets us.

**Comment by jpstroop** [comment]
If IIIF-speak, the Sequence is just a list of Canvases. Ranges are lists of Canvas URIs and other Range URIs. 
In PCDM speak I think they're all just different orders.

**Comment by jpstroop** [comment]
> In PCDM speak I think they're all just different orders.
One of which is flat (the sequence) and the other of which has more structure.

**Comment by tpendragon** [comment]
Wouldn't that make workflow troublesome? You'd have to re-order in two places, when likely all you want is logical structure.

**Comment by jpstroop** [comment]
I'm saying the orders can be completely independent. Use the sequence as
the point of departure for any logical structure, but changing the order in
the structure doesn't change the sequence.

**Comment by tpendragon** [comment]
I can try it, but I wonder if it's expected that the order differs between the two

**Comment by jpstroop** [comment]
It's definitely a challenge. We'll probably need to iterate a bit, and (obviously) see what @joycebcat thinks once we have something.

**Comment by jpstroop** [comment]
I the more I think about this, relative to the METS we have now, the more It the structural metadata editor will probably need to support reordering as well. :sweat:

**Comment by joycebcat** [comment]
I've been reading this, but not really following the implications.  I guess if we have selected images 3-5 to be part of sectionA, and then we realize an image was missing and image 12 is added and positioned in the physical structure between image 3 and 4, it would also need to be part of sectionA.  I don't want to have to fix image ordering issues multiple times.  Trey's comment some time ago about the reordering interface and the structural MD interface being the same makes sense in that regard.

**Comment by jpstroop** [comment]
>  I don't want to have to fix image ordering issues multiple times.

This is what happens with the METS now, right? There are up to (3) structMaps, one that is flat, and is used for paging, and up to (2) more, one for the physical structure and one for the logical structure. If images are found to be out of order, all three need to change.

The use case hasn't come up here, but is has in the IIIF and PCDM communities, that multiple different orders may be desirable, e.g. to support dis-bound and reassembled MSS, or other loose-leaf sorts of items. I don't know that we need to support multiple sequences yet, but tying the order of of one sequence to the structural metadata feel like we'd be starting to close that door.

I'm also afraid that making a change in the sequence propagate across the other structures might be really hard, from a code perspective.

**Comment by joycebcat** [comment]
If the logical structMap is messed up because of imaging problems, I re-generate the structMap from the original spreadsheet once the image issues are sorted out.  It doesn't have to be re-done from scratch, just slightly adjusted to accommodate the change.  I'm concerned about all necessary changes being made if they are all separate.  An added images gets dragged to location 5, fine.  Also have to drag added image to location 5 for the logical structMap.  Also have to drag added image to location 5 for pagination structMap.  You have a rosier view of human nature than I do if you think they will all be done properly all the time.

**Comment by jpstroop** [comment]
We can iterate on it, but right now my sense is that there's as much
likelihood of the application getting it wrong as a human. And we don't
have to write any extra code for the human to get it wrong! ☺

**Comment by joycebcat** [comment]
OK, as long as functionality is there, we can control via procedure.

**Comment by jpstroop** [comment]
OK. To be clear, I'm not saying no, only that there are enough other
challenges with this first pass that I don't think we should pile this on
just now.

**Comment by joycebcat** [comment]
Oh, absolutely!  Not needed for first pass.  Glad to know not completely ruled out.
