### ISSUE TITLE
If a FileSet has a dc:title value, use it as the label instead of ebucore:filename

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#183]
The FileSet renaming updates the dc:title value.  That should be used in the ScannedResource list of FileSets, if it's available.

**Comment by jpstroop** [comment]
I wonder if `rdfs:label` might be more appropriate?

**Comment by escowles** [comment]
:+1:  to putting the user-supplied page number in `rdfs:label` instead of `dc:title`.

**Comment by escowles** [comment]
On closer inspection, FileSet is just using dc:title because that's what CurationConcerns::RequiredMetadata does.  So #230 just updates the views, but doesn't change the predicate being used.

Should we open a CurationConcerns ticket to change the predicate?  I agree rdfs:label is a better fit, but on the other hand I see the attractiveness of saying every object has a dc:title value.

**Comment by jpstroop** [comment]
Ugh. I buy the "every object has a dc:title" argument. One could also argue that page numbers (regardless of the predicate) are contextual, and really belong on the Proxy. I'm not sure I'm ready to go there...

**Comment by escowles** [comment]
Yes, putting the page numbers on the proxies would make sense, but I agree it's an unnecessary complication right now.  I would prefer using rdfs:label for the page numbers, but I could live with dc:title for now.

**Comment by jpstroop** [comment]
I think we should stick w/ title for the sake of interop., but it does make me a little uncomfortable.
