### ISSUE TITLE
Add metadata to IIIF manifest

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#192]
Make sure the language (and, more importantly, the script) is in the `metadata` pool so that we can get right-to-left display working. (Clients are likely to support it yet, but we'll need to get it working).

**Comment by jpstroop** [comment]
@tampakis can you think of a way we can use the Traject processing in Plum?

**Comment by tampakis** [comment]
Shouldn't be hard. For Voyager records right? We would pull down the record from bibdata, call Traject's [map_record](https://github.com/pulibrary/orangeindex/blob/development/spec/lib/config_spec.rb#L15) method, which returns a hash of all the fields Traject is configured to handle. the value for the hash key is always an array even for single-valued fields.

**Comment by jpstroop** [comment]
See #315 (this is almost a dupe) and pulibrary/marc_liberation#58

**Comment by tampakis** [comment]
This is going to happen in bibdata.

**Comment by tpendragon** [comment]
@tampakis bibdata will return the metadata that Plum needs to pull, but at the end of the day it needs to be sitting in the metadata container at places like https://hydra-dev.princeton.edu/concern/scanned_resources/ng451h574/manifest

**Comment by tampakis** [comment]
oh sorry, i had thought that #315 was about that work and that this issue was more about getting the proper metadata in the IIIF manifest from Voyager
