### ISSUE TITLE
Should we allow non-browse everything uploads at all?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#198]
Right now we don't have a use case that doesn't include making sure files come in in order.

**Comment by tpendragon** [comment]
This is a question for Roel, I think. I just assumed being able to quickly upload a single file from a local disk and then ordering it to the right place was useful.

**Comment by jpstroop** [comment]
ping @roelmoon: Is there ever a case where it would be more efficient for you to upload files more quickly, but in no particular order? This would 

Standard uploader:
 * Faster
 * From _any_ machine
 * fFles arrive out and will be out of order until re-ordered in the UI you saw yesterday
 * (Maybe useful for digitizing photograph collections, GA materials)

"Browse Everything" uploader:
 * One file at a time, so slower
 * Files arrive in the order in which they sort and will be sorted that way in the repo
 * Files must be uploaded from a particular directory (yesterday we demo'ed from the Isilon storage, but it would probably wind up being your staging server)

You _can_ have both, I'm just wondering if there is a use for the first ("standard").

**Comment by jpstroop** [comment]
@tpendragon makes a good point...you might want to be able to do corrections without first sending the file to the staging server.

**Comment by rmoon** [comment]
I think this depends on who has to do the reordering with the standard uploader. Time wise, is standard upload plus reordering less than browse everything upload?

**Comment by jpstroop** [comment]
For books, I think reordering would be a big pain, because you'd have to look at the images, and probably in greater detail than thumbnails would allow. It would definitely take more time, and, more importantly, more human time.
