### ISSUE TITLE
Review workflow states per 12/1 discussion

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#211]
@escowles can you add the whiteboard photo?

See also #205

**Comment by escowles** [comment]
![img_2393](https://cloud.githubusercontent.com/assets/856924/11530241/08d1eff4-98c1-11e5-9610-42e1a22152f5.jpg)

The ingest workflow is basically:
Pending => Metadata Review => Final Review => Complete

The exceptional workflows are:
Complete <=> Needs Attention
Complete <=> Takedown => Delete
