### ISSUE TITLE
Revise view & edit pages

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#212]
There should be three views:

1. Default view (viewer, metadata summary, and file upload widgets)

    ![default](https://cloud.githubusercontent.com/assets/856924/11592203/05e312d6-9a6b-11e5-9c8c-eaa2eab753c7.jpg)

2. Files editor (bulk rename, reorder, file actions, structure)

    ![file-editor](https://cloud.githubusercontent.com/assets/856924/11592204/05e9263a-9a6b-11e5-9797-02078f77d102.jpg)

3. Metadata editor

    ![md-editor](https://cloud.githubusercontent.com/assets/856924/11592205/05ee6c94-9a6b-11e5-9af8-99744ebba637.jpg)

**Comment by eliotjordan** [comment]
Upload widget on bottom of the bulk editor.

**Comment by escowles** [comment]
Updating wireframes with actual drawings:
![1-default-view](https://cloud.githubusercontent.com/assets/856924/11664520/4430644c-9db0-11e5-9cbd-110f6e6824ae.png)
![2-bulk-editor](https://cloud.githubusercontent.com/assets/856924/11664521/443a400c-9db0-11e5-8160-e0d1f8da7f96.png)
![3-metadata-editor](https://cloud.githubusercontent.com/assets/856924/11664522/443dffe4-9db0-11e5-92ec-62059ba028dc.png)

I think part of the confusion was we said we'd iterate on the uploader on the default view, and then move it to the bulk editor when it was ready.

**Comment by eliotjordan** [comment]
I thought I understood the diagrams when I took the ticket, but as I go further in, I'm not so sure.

1. As far as I can tell, the current metadata editor already looks like the diagram, only with the addition of the rights section. Am I missing something?

2. In the scanned resource default view, are we removing the 'File List' section or is that just bundled in with 'Metadata Summary'?

3. On the upload section, is the idea this functionality eventually moves to the bottom of the bulk editor?

  Is this what we have in mind?

![screenshot 2015-12-14 12 36 14](https://cloud.githubusercontent.com/assets/784196/11788533/89749b96-a25f-11e5-8169-803a59ab208e.png)

  On the photo of the dry erase board, it looks more like this:

![screenshot 2015-12-14 12 41 05](https://cloud.githubusercontent.com/assets/784196/11788626/059b8324-a260-11e5-8c3d-785cddc999cf.png)

**Comment by escowles** [comment]
Eliot-

1. I don't think you're missing anything -- the edit metadata view is unchanged (leaving out rights was an omission on my part).

2. Yes, we want to remove the File List and assume people will use the bulk editor to work with the files.

3. I think it's fine to stick with a list view of the files being uploaded, so there's no need to work up a new grid view of uploading files.
