### ISSUE TITLE
Implement / fill out roles

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#213]
#### Admin
 * See Everything
 * Manage Roles
 * Assign "Complete" status
 * Delete Objects (any status)
 * Delete Images (any status)
 * + Image-Editors
 * + Editors

#### Image Editors
 * (i.e. Studio Techs and Mudd Tablet people)
 * Create Objects
 * Delete images _that they added AND aren't part of objects that have an ARK_
 * Delete objects _that don't have an ARK_
 * Upload images
 * Download Original
 * + Editors

#### Editors
 * Reorder images
 * Edit Object metadata (Change Bib ID, Set final review, etc.)
 * Bulk label
 * Edit Structure
 * (NOT Download)
 * + Curators

#### Fulfillers
 * Download Original
 * See Everything
 * Set "Needs Attention" status (and leave note)

#### Curators
 * View Everything, except state=pending
 * Set "Needs Attention" status (and leave note)

#### Generic User 
 * (i.e. on campus OR logged in)
 * See Public
 * See Campus-only
 * Set "Needs Attention" status (and leave note)

#### Anonymous
 * See Public
 * See IIIF Auth Service

**Comment by escowles** [comment]
Two of the actions specifically called out for Editors are:
* Change Bib ID
* Set final review
We could create custom actions to allow Editors to do only these actions without allowing them to edit the record metadata.  But given the name of the role, shouldn't they also be allowed to edit the metadata?

**Comment by jpstroop** [comment]
Not following...

>  given the name of the role, shouldn't they also be allowed to edit the metadata?

What metadata aren't we allowing the Editors to edit?

**Comment by escowles** [comment]
It doesn't explicitly say that they can edit the item metadata.  It says they can change the Bib ID, set final review, edit the structure, bulk edit.  But editing the main metadata isn't listed either way.

Given your reaction, I'm assuming they can edit the item metadata.

**Comment by jpstroop** [comment]
Ah, I see, so the few fields we do have right now. Yes, I think we should allow it.
