### ISSUE TITLE
ScannedResource should link to parent Multi-Volume Work

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#220]
When a ScannedResource is part of a Multi-Volume Work, the show page should link to it.

**Comment by escowles** [comment]
This is probably creating a new route for the scanned resource in the context of a particular multi-volume work: `/concern/multi_volume_work/:mvw_id/scanned_resource/:sr_id/`

**Comment by eliotjordan** [comment]
Start with "Back to Parent" button to the left of title. Maybe breadcrumb later.

**Comment by eliotjordan** [comment]
Closed by #234
