### ISSUE TITLE
Bulk labelling UI improvements

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#221]
* Display a flash message after applying bulk labels
* Display the filename in addition to the user-modifiable page number/title

Related to #217

**Comment by jpstroop** [comment]
Piling on more here, let me know if you'd like separate issues for any/all.

![screenshot from 2015-12-07 17-35-57](https://cloud.githubusercontent.com/assets/999701/11641942/22c06cfa-9d09-11e5-9ee5-5d5bcee9e959.png)

 * [ ] Radio buttons are funny
 * [ ] Once I've selected any box, I'm forced to always have one selected. I'd expect to be able to click outside (or elsewhere) and have none  selected
 * [ ] We'd talked about a changing the mouse pointer to a hand when you can drag, ala Trello
 * [ ] Minor, but I think the black border around the draggable boxes should go.
 * [ ] Assume we'll have a tiled view after #212? Reordering doesn't really work (from a UI perspective) in a vertical list. Maybe it would with a shorter lines/smaller thumbnails?

**Comment by tpendragon** [comment]
What browser for the weird radio buttons?

You can select outside the box, but it's a tiny border that's allowed. I'll see if I can do something about that.

:+1: to mouse pointer.

Borders are gone in https://github.com/pulibrary/plum/pull/233. Not necessary with panels.

Tiled view added in https://github.com/pulibrary/plum/pull/233. Check out the screenshot.

**Comment by jpstroop** [comment]
* Browser is Chrome Version 47.0.2526.73 (64-bit)
 * I think I'd expect the panel-body div to change somehow when I select it, rather than the area outside it. I see what you mean about deselecting, now that I know. Any way we can make it bigger would help.
 * I missed #233, or maybe you were working on it while I was writing this. Sorry! :blush:

**Comment by jpstroop** [comment]
Outstanding bullet opened as #241
