### ISSUE TITLE
Be able to mark as needing review again

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#23]

**Comment by escowles** [comment]
Right now we have just "pending" and "complete" -- is this just moving back to "pending"?  Or do we need a third state called "review" or something like that?

**Comment by tpendragon** [comment]
Need some clarification from @roelmoon and @joycebcat about what happens here. From what I remember, this is like..."something's changed (I've uploaded a new page or something), someone please look at it - when that person marks it as complete again, don't mint an ARK again"

**Comment by joycebcat** [comment]
@tpendragon Yes, we might need to update the bibliographic record, or add images, or re-sort images.  If there are behaviors (like minting an ARK) that should only happen the first time around, we should have a separate status for it.  A different status would also be helpful for workflow.  We would know that a number of general conditions have already been met.
