### ISSUE TITLE
Provide a way to see a larger version of the image in sequence (and structure) editors

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#236]
When supplying page numbers users are like going to need to be able to zoom in on an image and check the pagination or foliation without losing their work. A rare case where a modal may be a good idea.

Maybe clicking on the image (red box below) opens OpenSeadragon in a modal, similar to what happens in the [Image Browser](http://diglib.princeton.edu/tools/ib/) (campus only) now?

![screen shot 2015-12-08 at 3 01 48 pm](https://cloud.githubusercontent.com/assets/999701/11666944/fae24866-9dbc-11e5-9420-4b2e79249176.png)

**Comment by jpstroop** [comment]
Here's an example of a simple OSd modal in the PUDL: http://pudl.princeton.edu/boundart.php?obj=9593tv16p

**Comment by tpendragon** [comment]
Dragging to this sprint because it seems important.

**Comment by jpstroop** [comment]
:+1:

**Comment by jpstroop** [comment]
Heh.

> like going to.. 

Totally 😎

**Comment by tpendragon** [comment]
Branch at https://github.com/pulibrary/plum/tree/osd_modal_viewer fixes it, but it depends on the structure editor, so when that's merged I'll send a PR.
