### ISSUE TITLE
Add startCanvas to sequence

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#239]
Last predicate: here: http://iiif.io/api/presentation/2.1/#linking-properties

**Comment by tpendragon** [comment]
@jpstroop Is there ever a time where the thumbnail canvas != start canvas?

**Comment by jpstroop** [comment]
Definitely. Often they'll want to choose, e.g., an illumination as the
thumbnail, but the start should be something more logical. I suspect this
will happen even more once it's easier.

-Js

Sent via mobile. Please excuse typos, brevity, etc.
