### ISSUE TITLE
Deleting FileSet causes error when reordering

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#249]
Whn a FileSet is deleted, reordering the elements on the bulk edit pages causes an error.

```Order given has the wrong number of elements (should be #{n})```

![screenshot 2015-12-15 17 53 00](https://cloud.githubusercontent.com/assets/784196/11826735/16199a6a-a355-11e5-928a-ab6939e42b9f.png)

**Comment by tpendragon** [comment]
This makes sense - deleting a file set doesn't delete it from its orderings, which I think has an AF::Aggregations issue - https://github.com/projecthydra-labs/activefedora-aggregation/issues/72, or at least it's related. (I don't think Fedora deletes the proxy, but it does delete the #proxyFor statement)

**Comment by tpendragon** [comment]
I think it's a resurgence of projecthydra-labs/activefedora-aggregation/issues/21

**Comment by tpendragon** [comment]
Closed when we updated CurationConcerns in https://github.com/pulibrary/plum/pull/305

**Comment by eliotjordan** [comment]
:+1:
