### ISSUE TITLE
As a user I should be able to ask for a PDF representation of the book (rights permitted)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#25]

**Comment by flyingzumwalt** [comment]
Questions (@jpstroop):

* Where should generated pdfs be stored?
* What should the filenames of generated pdfs be set to?
* What metadata should be embedded in the pdf?  Maybe a URI for the scanned_book?

There's a first pass at this functionality in the pdf branch.  Here's what it does: 
* `scanned_book.to_pdf` generates a Prawn::Document with a page for each generic_file in the book
* Each page in the pdf containins the original_file from the corresponding generic_file object
* Most of the scanned_book metadata gets dumped into the PDF's EXIF
* `scanned_book.render_pdf(file_path)` renders the pdf file 

Notes: (see #64)
* I'm currently just grabbing the .original_file.content from each generic_file.  This should be changed once JP2 support is set up
* you must make sure that images don't exceed the page size.  Default page size is LETTER (612.00 x 792.00).  Currently I'm just telling prawn to limit image height to 792.00.

**Comment by tpendragon** [comment]
@jpstroop Can we close this? Maybe open an issue for adding metadata to the PDF?

**Comment by jpstroop** [comment]
:+1:
