### ISSUE TITLE
Do we need representative media?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#259]
Edit view has a form to this; for scanned books and maps I think a thumbnail is fine.

**Comment by escowles** [comment]
I'm not clear on what the difference is.  Is it that thumbnail is an arbitrary image URL, but representative media would use a thumbnail image from a repository object?

**Comment by jpstroop** [comment]
Something like that...I think the distinction may be inherited from Sufia? Right now it looks like we're essentially allowing user two select two different images.

**Comment by escowles** [comment]
Right, the UI is presenting the same options in both cases right now, which is not good.  So we should pick one or the other.

**Comment by jpstroop** [comment]
I vote for thumbnail

**Comment by escowles** [comment]
I looked up the predicates in the EBUCore ontology and representative media seems more appropriate for media than books/images, e.g. a film or audio clip.  So thumbnail is definitely what we want.
