### ISSUE TITLE
Generate JP2s on ingest

### ISSUE THREAD

**Issue by terrellt** [pulibrary/plum#26]

**Comment by terrellt** [comment]
I assume Kakadu is the way to do this? I've never used it directly before - is there a ruby binding?

**Comment by jpstroop** [comment]
Yes. No bindings, but I added a wrapper in hydra-derivatives a couple of
years ago (I assume it made it through this summer's refactoring).

I'll have to get our exact recipe from @roelmoon tomorrow.

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by terrellt** [comment]
Gotcha. https://github.com/projecthydra/hydra-derivatives/blob/master/lib/hydra/derivatives/jpeg2k_image.rb

**Comment by jpstroop** [comment]
More specifically: https://github.com/projecthydra/hydra-derivatives#jpeg2k-directives

And here are the recipes we used in the LAE project: https://github.com/pulibrary/pul-store/blob/development/config/pul_store.yml.tmpl#L112-L142

**Comment by jpstroop** [comment]
@roelmoon can you confirm that the recipes above are still correct?

**Comment by rmoon** [comment]
This is correct for 10:1 compression. We also have a 20:1 and lossless recipe.

**Comment by jpstroop** [comment]
Would it make sense to be able to choose the recipe as part of the ingest
process?

If so, you'd need to be able to replace if you got it wrong.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jpstroop** [comment]
@eliotjordan is it possible (and if so, can you provide instructions on how) to spin up [loris-docker](https://github.com/loris-imageserver/loris-docker) as part of our dev environments so that derivative JP2s can be written to the container's storage?

**Comment by rmoon** [comment]
@jpstroop regarding recipe choice, my 2-cents is that there should be a choice, but where to make the choice might be worth a short discussion. The vast majority of what we put online is 10:1, but there are occasional higher compression rates needed (newspaper OCR projects) as well as lossless (recall engravings).

**Comment by jpstroop** [comment]
@rmoon Those are the cases I was thinking about too.

Do you have two Github handles?

**Comment by rmoon** [comment]
@jpstroop I think rmoon is my user name.

**Comment by eliotjordan** [comment]
@jpstroop Spinning up a docker container via a rake task is easy. Is that what you had in mind? Getting that working properly in Travis as part of integration testing is tricky. I looked into that awhile back. Maybe they've improved their support, or perhaps Circle has better docker integration.

**Comment by jpstroop** [comment]
I think skipping the specs in CI would be fine (though maybe circleci 
does have better support?).

I also think it could be similar to hydra-jetty, i.e. we expect it to be 
running when you kick off the specs.

So, ideally there would be rake tasks to install and spin it up.

But, I still don't quit understand how you mount the container's storage 
on your local file system (using whatever protocol) so that you can 
write to it like any other dir, that is, I'd like to put images in 
`$MY_RAILS_APP/loris/foo/bar/baz.jp2` and have them be in 
`/usr/local/share/images/foo/bar/baz.jp2`, so that I can hand 
`foo%20bar%20baz.jp2` to the image server as the ID part of the image 
request. Make sense?

**Comment by eliotjordan** [comment]
Mounting a local directory in the container is easy. The task would run a command like:

**Comment by eliotjordan** [comment]
Mounting a local directory in the container is easy. The tasks would execute a command like:

    $ docker run -v ./tmp/loris:/usr/local/share/images lorisimageserver/loris

If you create ```baz.jp2``` at ```$MY_RAILS_APP/tmp/loris/foo/bar/```, the image will be accessible at  ```http://{dockerhost ip}:{port}/foo%20bar%20baz.jp2``` as expected.
