### ISSUE TITLE
Create actions for state transitions

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#266]
Reviewing the roles and actions in #213, there are a few state transitions that users should be allowed to perform (e.g., flagging for review), even though they shouldn't have permission to edit the record.

To isolate these state transitions and allow users to perform them, we should create actions for at least:
* flag (everyone except anonymous)
* final_review (editors/image editors)

**Comment by jpstroop** [comment]
That sounds about right to me. For the initial workflow, I don't know that image editors need to be able to mark final_review, but I don't see why it would hurt.
