### ISSUE TITLE
Add License info to the repository

### ISSUE THREAD

**Issue by flyingzumwalt** [pulibrary/plum#3]
... and if you're using Apache2, add the badge (see other hydra repos for the link)

**Comment by jpstroop** [comment]
I tend to prefer [New BSD](http://choosealicense.com/licenses/bsd-3-clause/), but it may be easiest to stick w/ Apache. PUL doesn't have an opinion (_yet_, at least), does anyone else?

**Comment by terrellt** [comment]
I've always defaulted to GPL. Maybe apache is easier? I always wonder how much infrastructure we need to put in place to use it.

**Comment by jpstroop** [comment]
Princeton is always worried about people using the logo and brand, and having that explicitly stated (as it is in Apache, New BSD, and Mozilla) is probably a good idea. The main difference (I think) is an explicit patent/copyright grant. It's there in Apache and Mozilla, and not in New BSD.
