### ISSUE TITLE
Get IIIF-formatted descriptive metadata from bibdata

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#315]
This will solve the problem for metadata from Voyager; Finding Aids will need a similar service. Depends on pulibrary/marc_liberation#58

**Comment by jpstroop** [comment]
Structure coming from bibdata should have `label` (MARC 245), `description` (MARC 520), `metadata` (everything else)

**Comment by escowles** [comment]
Closed in favor of #442
