### ISSUE TITLE
Facets

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#354]
Remove publisher and creator, add language

**Comment by escowles** [comment]
Language is already configured as a facet, but we don't have a UI to edit it (nor are we getting it from bibdata).  Do we want to add those?  Should the UI have the same behavior as title (allowing the user to edit either the source metadata id or title/lang, but not both)?

**Comment by jpstroop** [comment]
We can get if from bibdata, at least for bib resources, we just aren't:

https://github.com/pulibrary/pul_metadata_services/blob/master/lib/pul_metadata_services/bib_record.rb#L117

but I suspect that will be important for OCR; I think it might only make sense to allow editing of the language when you can't map from the MARC language to something Tessaract supports--and yes, being able to choose the language when when we don't have one from bibdata makes sense.
