### ISSUE TITLE
Thumbnail/cover service

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#360]
We're not able to get covers from Google for most of the stuff we've digitized. Having {id}/thumbnail return the thumbnail jpg would be very useful for orangelight.

**Comment by tpendragon** [comment]
When Orangelight indexes should it not just pull from the IIIF manifest?

**Comment by jpstroop** [comment]
I suppose it could...

**Comment by jpstroop** [comment]
Reopening this--I think we we should reconsider. Being able to pass a bib id to a service w/o having the Manifest or NOID would be useful, and the Manifest may be subject to access controls but a thumbnail still available under fair use, and RBSC is talking about digitizing a bunch of covers and dedication pages...

**Comment by tpendragon** [comment]
Sounds good. Do we want a discover-manifest-by-bib-id service which embeds the thumbnail if there's permission, a route which redirects to the IIIF thumbnail URL, or a proxying service so that the route itself is the thumbnail?

**Comment by jpstroop** [comment]
I think being able to hit, e.g.

http://plum.princeton.edu/thumbnails/{src_metadata_id}

and get `303`'d to a jpg from the image server would be ideal. Do you see any reason that wouldn't work?

I don't want this to get out of control, but I suppose being able to ask for batches, the way we do now with Google, would be nice too...

**Comment by tpendragon** [comment]
:+1: That's easy enough.

Just copy google's batch thumbnail API? Do you know of a standard format for such a thing?

**Comment by jpstroop** [comment]
I don't. Trying to think if any IIIF structures make sense, but it all seems like overkill.

**Comment by jpstroop** [comment]
Copying Google's API seems like overkill too, no? Seems like POSTing an array of IDs and getting back something like `{ "id" : "uri.jpg", "id" : "uri.jpg" }` would suffice?

**Comment by jpstroop** [comment]
maybe limit it to up to _n_ at a time to prevent DOS attacks?

**Comment by tpendragon** [comment]
Rate limiting in ruby is probably just as expensive as doing the redirect.

**Comment by tpendragon** [comment]
Why would we need a bulk thumbnail service anyways, if there's a known URL that returns an image? We'd only need one if sometimes there wasn't a thumbnail, yeah?

**Comment by jpstroop** [comment]
Bulk means one request to Plum + many requests to image server. One at a time means many requests to Plum -redirect- many requests to image server. No?

**Comment by tpendragon** [comment]
Yeah. I wonder if it'd even be a problem though.
