### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by terrellt** [pulibrary/plum#38]

**Comment by jpstroop** [comment]
@kevinreiss / @axapu are there cycles available from you next week?

**Comment by jpstroop** [comment]
@kevinreiss / @axapu I didn't catch you yesterday. Any chance we can get some time this week?

**Comment by axapu** [comment]
@jpstroop Most definitely. I'll try to get this done by end of week.

**Comment by jpstroop** [comment]
Awesome, thanks @axapu!
