### ISSUE TITLE
Add rights note field, only shown when rights statement is "unknown"

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#388]
See #74

**Comment by escowles** [comment]
Should we use the Europeana unknown rights status (http://www.europeana.eu/rights/unknown/), or is RightsStatements.org "Copyright Not Evaluated" a better fit?

**Comment by jpstroop** [comment]
2.3 InC-RUU seems close as well, or at least that's the primary use-case for "unknown" that I can imagine. Maybe show the note in that case?
