### ISSUE TITLE
Contrast on color images converted to grayscale

### ISSUE THREAD

**Issue by rmoon** [pulibrary/plum#392]
Brittle books: images converted to grayscale PDF for reprinting/binding should have improved contrast.

**Comment by jpstroop** [comment]
@rmoon what did you send the vendor for the pilot? What could you send them?

**Comment by jpstroop** [comment]
Bulk download for adjustment in Photoshop (or whatever) might be easier for us to accommodate. What would you need to download?

**Comment by rmoon** [comment]
Vendor will accept image files (jpg or tif) or PDF. For the test, we sent images files in RGB, they did a simple "convert to gray" but no contrast adjustment.

**Comment by jpstroop** [comment]
Assuming that someone will want to tweak contrast, PDF probably isn't the best thing to offer, right? If that's the case, what would you want to download? JPGs would be easiest for us, bt I'm thinking that wouldn't be a good idea because adjusting the contrast might require resampling? Or not?

**Comment by rmoon** [comment]
As discussed, eventually bulk download to manually generate Wert files.
