### ISSUE TITLE
CircleCI?

### ISSUE THREAD

**Issue by terrellt** [pulibrary/plum#4]
I usually like using CircleCI over Travis for projects which you don't need a matrix for (like Hydra heads). It's faster, does automatic parallelism, can cache even if you have dependencies, and lets you ssh into the build to debug it.

**Comment by jpstroop** [comment]
I've always wanted to try CircleCI. I'm :+1: to giving it a try.

**Comment by jpstroop** [comment]
Closed by f545a038dfc8d6632b5831270858ca4fe942dfdf
