### ISSUE TITLE
OCR should go in the repo

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#406]
It doesn't feel like a service derivative to me.

**Comment by escowles** [comment]
+1

**Comment by jpstroop** [comment]
What technical metadata do we want to go along with it?

**Comment by jpstroop** [comment]
Cicognara makes this, along w/ exposing the OCR as an AnnotationLists & Layers (is that #386?) a little more urgent.

**Comment by jpstroop** [comment]
hOCR to IIIF Annotation could be a nice gem.

**Comment by tpendragon** [comment]
HOCR should be in the repository and in the index.
