### ISSUE TITLE
Remove access policy from rights form

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#407]
I don't think we need it with what we have.

**Comment by escowles** [comment]
If we wanted to have more restricted access than what the rights statement allows, I assume we'd just use visibility for that (and add more visibility options for e.g., show only greyscale, etc.)?  That's the only kind of use case I was thinking might possibly go in access policy.

**Comment by jpstroop** [comment]
Ah, I see. I would expect that to be a series of checkboxes with options like No PDF, Grayscale only, Watermark... Thoughts?

**Comment by jpstroop** [comment]
Wait, re-reading, are you saying Access Policy would add more language explaining the additional restriction? Couldn't that just go in the existing rights text box? I'm not sure, but I don't think that will be a regularly occurring thing right now.

**Comment by escowles** [comment]
If there are several of them, then I guess they can't be shoe-horned into visibility.  In that case, I think a multivalued access policy is the right place for them (we can call them something different like "access rights" or "restrictions" or whatever).

I think it would be good to have URIs for the various restrictions, and to have that trigger both the behavior and any display values we want to show -- that seems better and more likely to be consistent than entering in boilerplate in the rights note.

**Comment by jpstroop** [comment]
Yeah...it's a funny space between visibility ('I can get something') and what you can get ('but maybe not a PDF'). I don't think we should over develop this part just yet because this rights group seems to want to talk about this in addition to the broader topic of rights statements.

**Comment by escowles** [comment]
For today, should I just remove the Access Right menu, or put in some checkboxes for No PDF, Grayscale, and Watermarked?

**Comment by jpstroop** [comment]
I think just remove for today. Thanks!!

-Js

Sent via mobile. Please excuse typos, brevity, etc.
