### ISSUE TITLE
Second iteration of PDF Cover Page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#415]
Getting something up had the desired effect. Here's what they would like to see in a second pass (with actual headings, as quasi-styled below). Bonus points for a PUL logo:
 * http://library.princeton.edu/princeton-university-library-logos
 * https://github.com/pulibrary/pul_graphics/tree/master/pul

## Title (native if available)

Rights Statement Blah blah blah; Try to get a space between the paragraphs

## Princeton University Library Disclaimer 
(This is revised ... the links in the previous iteration have to go)
Princeton University Library claims no copyright governing this digital resource. It is provided for free, on a non-commercial, open-access basis, for fair-use academic and research purposes only. Anyone who claims copyright over any part of these resources and feels that they should not be presented in this manner is invited to contact Princeton University Library, who will in turn consider such concerns and make every effort to respond appropriately.

## Citation Information
Creator (incl native and romanized)
Title (incl native and romanized)
Edition stmt
Physical Description
Abstract
Holding Location
Collection Name (from EAD)
Call Number / Collection Number

## Contact Information
Holding Location and Phone, Address, whatever we have

## Download Information
Stamp Date Rendered 
Stamp Date Downloaded (if possible)
Available Online at: [Persistent URL for HTTP rendition ... in Plum I guess]

**Comment by escowles** [comment]
It looks like a few fields of the citation info aren't in the JSONLD now, and a few more are present but not mapped:

* edition is in the JSONLD, but not defined in the context.  Should we use bf:editionStatement?
* we have a field labeled "description" using dct:abstract — do we want to re-label it abstract and use dc:description for the physical description? or use dct:extent for the physical description?
* call number isn't in the JSONLD, but is in the MARC, so we can add it
* is collection number also EAD-specific?
