### ISSUE TITLE
Top level iiif:Collection

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#420]
[Thread on the IIIF list suggesting this approach to manifest agggregation](https://groups.google.com/d/msg/iiif-discuss/r1ANaZG-BQo/hcezi28cBAAJ). We should do this. I don't know if it's the best solution, but since since someone is finally taking the lead (it's been discussed forever, but nothing has ever really happened) I suppose we should play ball.

**Comment by tpendragon** [comment]
@jpstroop Don't we have this already at http://hydra-dev.princeton.edu/collections/manifest ?

**Comment by jpstroop** [comment]
Ah, so we do!

Not sure I'm crazy about the route (/collections or /iiif/collections would be better), and the "viewingDirection" and "viewingDirection" shouldn't be there, but looks good otherwise. Want a separate issue, or just recycle this one?

**Comment by tpendragon** [comment]
@jpstroop Recycling seems best. My assumption was that route was the most guessable. I think I'd vote for /collections if we changed it, but even that's a little weird without a content type for IIIF manifests.

**Comment by jpstroop** [comment]
OK, if we're recycling then I'll keep this open for getting right of viewingHint and viewingDriection from /collections.

My only concern about the route is that we may want `/collections` to render as HTML, and I hate forcing anyone to rely on conneg. The solutions I see are:
 1. Support conneg AND poor-man's conneg, i.e. `/collections` or `/collections.html` get you HTML and `/collections.json[ld]` gets you JSON. Practically speaking, all of the IIIFers will wind up using the poor man's `.json` URI (slamming the door on YAML-LD forever! :wink:), and our implementation contradicts the pattern recommended in the specs.
 2. Put `/iiif` somewhere in the route and keep the URI cool.

Unless there's something I'm missing, I think I prefer #2.

**Comment by tpendragon** [comment]
@jpstroop `/iiif/collections` seems fine then, so long as we don't need to switch the manifest URLs to `/iiif/manifests/123` or something.

**Comment by jpstroop** [comment]
I think that's fine

**Comment by tpendragon** [comment]
Closed by #432
