### ISSUE TITLE
Host Universal Viewer at a URL

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#427]

**Comment by tpendragon** [comment]
So this is hosted, but we can't use it for Plum because the page in the iFrame is what loads the manifest. Since it's on a different domain/infrastructure, it doesn't have permission to private manifests.

**Comment by tpendragon** [comment]
Maybe this is just a CORS problem.

**Comment by tpendragon** [comment]
Okay, so it's two problems.

1. CORS. This is fixed in production and in development it can be fixed with [rack-cors](https://github.com/cyu/rack-cors)
2. The URL for the manifest is relative to http://uv-princeton.edu. Which is fine in production, but in development it's all localhost:3000. I'm not sure how to solve this - do we require spinning up a local instance of UV for seeing what the viewer looks like in dev?

**Comment by tpendragon** [comment]
Nope, problem 2 isn't a problem. It's relative to the requesting host, but is still throwing a 401 unauthorized...

**Comment by tpendragon** [comment]
To do this we'll have to implement token-based authentication, according to http://iiif.io/api/auth/0.9/#access-token-service

**Comment by jpstroop** [comment]
@mejackreed and @cbeer did this last fall. Pointers?

**Comment by mejackreed** [comment]
Originally implemented client side here: https://github.com/sul-dlss/sul-embed/commit/51a7eb4217cae22770f403f409854fd6076f3c73 also something similar here: https://github.com/sul-dlss/iiifManifestLayouts/commit/3471ff1fcb6bf9b3b61f4f98ea49ae6e5cadd062
