### ISSUE TITLE
Check bibdata events.json for MARC metadata updates

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#428]

**Comment by tpendragon** [comment]
So if I'm reading this events stream right, the thing to do is:

1. Check events.json for unprocessed events with a dump_type of CHANGED_RECORDS
2. Pull that dump, parse all the bib IDs in the update_ids array, and trigger a refresh of those records

Do we want to do anything for the deleted IDs?

**Comment by tpendragon** [comment]
Meant to ping people. @tampakis @jpstroop Sound right?

**Comment by tampakis** [comment]
That sounds right. I would imagine if something needed to get deleted from plum we would find out in a way that is different from checking if the Voyager record was deleted.
