### ISSUE TITLE
Create a CURL script for benchmarking ingesting items into Fedora.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#449]

**Comment by escowles** [comment]
Comparing processing times for several items on two different machines found that a significant majority of processing time is spent on OCR (about 66%).  JP2 generation with Kakadu was the most improved by using a machine with more CPU power, and performing characterization with FITS benefitted the least.

See full results here: https://docs.google.com/spreadsheets/d/1e2bhNsMgGvIkSGyxQyH73PMv-3xSNsyvf_h2C2Y6mSA/edit

Script: https://gist.github.com/escowles/4c9b81e06e39c24dfca3
