### ISSUE TITLE
Set up demo server

### ISSUE THREAD

**Issue by flyingzumwalt** [pulibrary/plum#45]
Set up a demo server.  Auto-deploy from github master branch when there's a new green CircleCI build for that branch.

You need this so people can look at features/functionality without having to spin up a local copy of the app.

**Comment by flyingzumwalt** [comment]
@jpstroop

**Comment by jpstroop** [comment]
A machine has been requested. There's only a small chance we'll have it by the end of next week.

**Comment by jpstroop** [comment]
Machine is ready. I wonder if we should try: https://circleci.com/docs/introduction-to-continuous-deployment

**Comment by kevinreiss** [comment]
Seems like a good idea since this is a new project and I think continuous
deployment is where you ultimately want to be.

**Comment by terrellt** [comment]
If I set up bot deploys, then auto-deploy is a part of that.

**Comment by jpstroop** [comment]
:+1:
