### ISSUE TITLE
Which MARC relators do we use?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#450]
@joycebcat Do you have a list of the MARC relators we currently use?

@mzelesky Any way we could get a report?

**Comment by joycebcat** [comment]
@jpstroop @mzelesky I assume you mean any MARC relators we have in the catalog, right?  We have RDA text, MARCrelator codes and text, Chinese RB project, and a smattering of other stuff.  We should be prepared to support the three named categories whether presented in text or coded versions.  I don't have a list of what currently exists in Voyager.  To find out, we would need to look for |e and |4 on main and added entries, and |j on 111 or 711 fields.

**Comment by jpstroop** [comment]
Thanks! Yes, in the catalog, and yes those fields. I knew about the codes and text (and didn't know that RDA adds more, I thought it just put them into categories and that because they sometimes repeat across categories, the list looks longer--are these available as LD anywhere?) Are the Chinese RB terms different as well? And, same question, are they available as LD anywhere?

**Comment by joycebcat** [comment]
@jpstroop The RDA relators I think are all at id.loc.gov now.  I don't think the general RB terms are linked data, but the list is here: http://rbms.info/vocabularies/relators/alphabetical_list.htm.  Sadly the Chinese project doesn't even have a definitive list of relators, there are some examples in their guidelines (http://www.eastasianlib.org/ctp/webinars/ChineseRareBook/CRBP_guidelines.pdf).

**Comment by jpstroop** [comment]
@mzelesky I had a chat w/ @joycebcat -- could you do a report of all of the unique `|e`s, `|4`s, and `|j`s as she describes above? She would like to review.

**Comment by mzelesky** [comment]
Yes, I will do that tomorrow morning . I was working on the 5xx report that relates to Princeton copy-specific information today. It took a bit longer than I anticipated.

**Comment by jpstroop** [comment]
:+1:

**Comment by mzelesky** [comment]
Ok, I have created 3 separate files for the relators, one for 'j' from the x11 fields, one for 'e' in the other heading fields, and one for '4' from all heading fields. I kept the subfield codes in as well, to make it easier to see any empty subfields.



[relators4dedupe.txt](https://github.com/pulibrary/plum/files/159331/relators4dedupe.txt)
[relatorsededupe.txt](https://github.com/pulibrary/plum/files/159333/relatorsededupe.txt)
[relatorsjdedupe.txt](https://github.com/pulibrary/plum/files/159332/relatorsjdedupe.txt)

**Comment by escowles** [comment]
Thanks, @mzelesky!

Looking at the reports, the "j" values mostly map to MARC relator labels, except for "commissioning body" and "sponsoring body" (which could map to sponsor).

The "4" values are mostly MARC relator codes, but there a few dates and other codes: NjP, "/bt", "8-0", "AUTO", "BIND", "SP1", etc. and a few labels "cartographer", "colorist", "issuing body", etc.

Removing the variants that are because of extra punctuation, etc., I come up with a total of 160 unique relators being used, which is a little more than half.  With that many in use, it may make sense to keep supporting all of them rather than trying to pick and choose which ones to keep (as opposed to mapping to a generic "contributor" field).

**Comment by jpstroop** [comment]
From my conversation with @joycebcat it sounds as though they're starting to add labels rather than codes. Not sure if these labels are in one of the other RDF dumps available from LC, but I don't think they're in the ntriples, which is what I used to build the JSON-LD context.

Joyce, can you fill in the gaps here? Where do the labels come from? @tampakis or @escowles may need to modify the traject config.

**Comment by joycebcat** [comment]
@mzelesky  The "e" file seems to terminate prematurely in the middle of a heading starting with v.

**Comment by joycebcat** [comment]
@jpstroop id.loc.gov is where most of the values are drawn from.  It uses the code version in the URI, but looking into the json for the entry, the text version is in there.

**Comment by mzelesky** [comment]
@joycebcat My apologies. I have redone that file.
[subfededupe.txt](https://github.com/pulibrary/plum/files/163956/subfededupe.txt)

**Comment by mzelesky** [comment]
@joycebcat Once more. The previous file included 76x through 79x. This one should do it.
[subfededupe.txt](https://github.com/pulibrary/plum/files/163986/subfededupe.txt)
