### ISSUE TITLE
Metadata from Bibdata showing up with question marks

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#452]
UTF-8 problems?

**Comment by tpendragon** [comment]
Fixed by @escowles via setting Tomcat's UTF-8 settings.

**Comment by escowles** [comment]
For posterity: to force Tomcat to use UTF-8 by default, add -Dfile.encoding=UTF-8 to the JAVA_OPTS environment variable in Tomcat's setenv.sh script.
