### ISSUE TITLE
Experiment with nailgun

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#458]

**Comment by escowles** [comment]
Nailgun creates a daemon which preserves the JVM state across multiple executions, in theory reducing the overhead associated with the JVM startup.  See https://github.com/projecthydra/hydra-file_characterization/issues/21 for more info on using Nailgun for improving FITS performance.

**Comment by escowles** [comment]
Running FITS with Nailgun, on a sample dataset of 98 TIFFs (~100MB each), was significantly faster than running it without Nailgun.  Normal execution took 479 sec, Nailgun execution took 296.

**Comment by grosscol** [comment]
What happens with the memory footprint?  I recall having a slow memory leak when I was using Nailgun with JRuby on Java7 VMs.
