### ISSUE TITLE
Use Hosted Universal Viewer

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#467]
Requires token auth

**Comment by escowles** [comment]
Is this still relevant now that we're using pul_uv_rails?

**Comment by jpstroop** [comment]
If we want to support arbitrarily embedding elsewhere (e.g. in a blog), is there any advantage either way?

**Comment by Mendonn** [comment]
Nah, we should just close this.

**Comment by jpstroop** [comment]
i.e. wrt IIIF Auth?

**Comment by tpendragon** [comment]
Nope. Only benefit would be if it were external it would be easier to upgrade in all places. I say we just close this.
