### ISSUE TITLE
Adding existing item to a collection fails

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#492]
Editing this item and adding it to a collection results in an error:

https://hydra-dev.princeton.edu/concern/scanned_resources/cr56n096b

The error in the logfile is:

https://gist.github.com/escowles/206ba1fa64b405a895e5

**Comment by tpendragon** [comment]
Fixed by https://github.com/projecthydra-labs/curation_concerns/pull/672 when it's merged.
