### ISSUE TITLE
File upload/thumbnail mismatch

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#495]
This uploaded file should be a page of text, but the thumbnail (and full view in UV) is a green/purple line drawing.

https://hydra-dev.princeton.edu/concern/file_sets/9p2909328

**Comment by jpstroop** [comment]
Image server cache?

**Comment by tpendragon** [comment]
That should only happen if the PIDs are being reminted, right?

**Comment by jpstroop** [comment]
Yes

**Comment by escowles** [comment]
so, now we have a concrete instance of needing to clear the cache - we should document what needs to happen to fix this.

**Comment by tpendragon** [comment]
I'm more concerned that the PIDs got reminted

**Comment by jpstroop** [comment]
> so, now we have a concrete instance of needing to clear the cache - we should document what needs to happen to fix this.

In Loris you mean?

**Comment by jpstroop** [comment]
Just to check if that's the case, I'm not sure where that docker image caches thumbnails, but find out and remove the contents of the directory.

**Comment by escowles** [comment]
The JP2, hOCR and thumbnail derivatives for the old file were updated in December, in `/opt/plum/shared/tmp/derivatives/9p/29/09/32`.  So I do think this just boils down to an identifier being reused.  Did we lose our pid minter state at some point?  In any event, I removed the old files and re-uploaded the TIFF in question (which seemed like the easiest way to regenerate the derivatives).

The loris cache files were in `/var/cache/loris2/9p/29/09/32`.  Removing them made loris regenerate them successfully.

**Comment by tpendragon** [comment]
Is our minter being stored in /tmp? Maybe that got cleared out?

**Comment by escowles** [comment]
Yes, it's in `/tmp/minter-state` -- I may have just removed everything in /tmp when I filled up the disk with the 800-page test object.

**Comment by tpendragon** [comment]
We should probably put it somewhere else.

**Comment by escowles** [comment]
Definitly, I've created a ticket for moving it: https://github.com/pulibrary/plum/issues/497

**Comment by jpstroop** [comment]
cap's shared directory seems like a logical spot?

**Comment by escowles** [comment]
Closing this issue (which was caused by a PID being reused).  See #497 for moving the minter state file to prevent deletion, and #499 for updating derivatives and clearing the image server cache when a new file is uploaded.
