### ISSUE TITLE
Universal Viewer grabs focus on show pages

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#498]
This slows down editing/viewing.

**Comment by tpendragon** [comment]
Issue created at https://github.com/UniversalViewer/universalviewer/issues/267

**Comment by escowles** [comment]
Looks like this can be avoided by embedding differently: see example page https://www.llgc.org.uk/blog/?p=11111

**Comment by jpstroop** [comment]
Seems like we could fix this in Plum now too.

**Comment by tpendragon** [comment]
We can, but the URL won't change to link to an image and fullscreen won't be true full screen. If that's fine, we should do it

**Comment by jpstroop** [comment]
Oh, bummer. Is there any other way to capture the viewer state in UV? That does seem like an important feature for workflow.

**Comment by escowles** [comment]
Being able to link to a page seems like a nice feature for OL too, though.

**Comment by jpstroop** [comment]
I agree, that would be ideal. Does UV expose the URL it's pushes to the address bar in some other way in this case?

**Comment by tpendragon** [comment]
I don't think so. Maybe in the share button, but I don't see how it would get the link right

**Comment by jpstroop** [comment]
Because it would link you to plum instead?

**Comment by tpendragon** [comment]
@jpstroop Just looked, it doesn't expose the URL anywhere.

**Comment by tpendragon** [comment]
Use embeddable version for plum, but not for Pomegranate.
