### ISSUE TITLE
IIIF predicates on books and pages

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#50]
Somewhat related to #32 in that these must be editable fields, though not descriptive properties. Will be required for #21.

(`sc` = `http://iiif.io/api/presentation/2#`)

__Scanned Books need:__

Viewing Direction (`sc:viewingDirection`). The value/object must be one of:
 * left-to-right (`sc:leftToRightDirection`) __(default)__
 * right-to-left (`sc:rightToLeftDirection`)
 * top-to-bottom (`sc:toToBottomDirection`)
 * bottom-to-top (`sc:bottomToTopDirection`)

Viewing Hint (`sc:viewingHint`). The value/object must be one of:
 * individuals (`sc:individualsHint`) __(default)__
 * paged (`sc:pagedHint`)
 * continuous (`sc:continuousHint`)

__Pages need:__

Viewing Hint (`sc:viewingHint`). The value/object must be one of:
 * non-paged (`sc:nonPagedHint`)
 * facing-pages (`sc:facingPagesHint`)

Label (`rdfs:label`)

**Comment by terrellt** [comment]
All dropdowns.

**Comment by terrellt** [comment]
@jpstroop I don't see the URIs for the acceptable values (IE `sc:leftToRightDirection`) in the spec, so I assume they won't resolve. Rather I just see literals as stand-ins - is this work that's in progress?

**Comment by jpstroop** [comment]
Hmm. The URIs are used in the the [JSON-LD context](http://iiif.io/api/presentation/2/context.json), and I thought that they did resolve to [this ontology](http://iiif.io/api/presentation/2/ontology.xml).

Paging @azaroth42: Any reason we can't make this so?

**Comment by terrellt** [comment]
Oh, that's interesting. The JSON-LD context layers a URI on the literal

**Comment by azaroth42** [comment]
While URIs SHOULD resolve to their appropriate term definitions, what's the requirement in particular?

`left-to-right` is `sc:leftToRightDirection` is `http://iiif.io/api/presentation/2#leftToRightDirection`
So it's a URI ... which doesn't resolve.

I put in a redirect from 2 to 2/ontology.xml on the iiif.io server and created a "Update the ontology" issue:  https://github.com/IIIF/iiif.io/issues/551

**Comment by terrellt** [comment]
@azaroth42 :+1: That'll fix resolution. Thank you.

@jpstroop Use the URIs for the forms? I ask because transforming the string `http://iiif.io/api/presentation/2#leftToRightDirection` to an RDF::URI in the right circumstances will require a number of overrides.

**Comment by jpstroop** [comment]
For now I think it's good enough help people know that the ontology exists. Thanks Rob!

**Comment by jpstroop** [comment]
Advanced by 8bc054d92edaad04324d10231d9768a8c78abd42 and 4c135a2915f0773142af9a6ece6b231bea192be2. Closing this and opening a new issue for form fields (#62).
