### ISSUE TITLE
PDF Options

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#511]
We need two flavors of PDF: Gray and Color, and an option to make a PDF not available at all.

Use case for Gray:
Smaller file, degraded quality w/ compression and 8 instead of 24 bit depth serves the reading use case while limiting it's use as a reproduction

Use case for Color:
Larger, but truer fidelity to the RWO, useful for printing 'preservation photocopies'

Use case for None:
Concerned curators.

Discussion on 3/29 suggested a we find a predicate to indicate the download availability, and URIs for `:true`, `:false`, and `:degraded`.

**Comment by tpendragon** [comment]
Do access controls fit into this? Can we get away with "no matter who you are if you can read it this is the pdf you get"?

**Comment by tpendragon** [comment]
If I was unclear, do curators need a color pdf and students a grayscale?

**Comment by jpstroop** [comment]
I get it. I would hate to tie them that tightly, seems like it could add complexity later. A curator should probably be able to change the value, so that if they're desperate they can change the value, download, and change it back, but my sense is that the setting should generally apply to all users.

**Comment by escowles** [comment]
It seems weird to limit what a user can do when they have the ability to edit the permissions to circumvent that limit.  Wouldn't it be better to just allow them to download the color PDF?  Maybe we should only apply the limits to users who can't edit the record?

**Comment by tpendragon** [comment]
I believe it was @flyingzumwalt who said something like "After you give them a PDF all bets are off." The reason to not change permissions would be that PDFs are email transfer formats - there's an argument to be made that whether or not a color PDF is floating around should be up to the policies surrounding that item.

**Comment by escowles** [comment]
For users who can edit the record to change the restrictions, we have two options:

1. Let them edit the permissions, briefly making the color PDF available to everyone
2. Just let them download the color PDF by virtue of their ability to do option 1 

I think option 2 is the better option.

**Comment by tpendragon** [comment]
Do we give them a red box, "This item was marked as not being available for color download by the public."? I recognize we probably don't need it, the users who can edit items in this system are almost certainly better versed in rights and distribution issues than I am, but maybe for clarity?

**Comment by escowles** [comment]
I think making it clear what is available to them vs. what is available to users is important.  So highlighting or changing the color, etc. of the PDF download button, having a note/tooltip, etc. makes sense.

**Comment by jpstroop** [comment]
> Maybe we should only apply the limits to users who can't edit the record?

I'm :ok: with that; I was just trying to keep it simple, and that seems simple. :smile: 

Re: PDFs in the wild (color or otherwise), frankly, the people who care about color vs. grayscale don't care for legal reasons in nearly all cases; it's usually about degrading access to the content or limiting the ability to further reproduce it. Matt is right, once a PDF is downloaded, whether it's one or 100, we've lost control, whether they believe it or not. This is as much about hearts and minds as anything else.

**Comment by tpendragon** [comment]
@jpstroop @escowles Opinions on where to put the download button? Down where the "File Manager" button is, but with a dropdown if they can get either B&W or Color?

**Comment by escowles** [comment]
That sounds fine — keeping all the buttons together for now seems like a good idea.

**Comment by tpendragon** [comment]
A predicate for "type of PDF which is available to unauthorized users" still feels weird to me. That being said, any options? Or do we just mint PUL#has_pdf and put in either the grayscale or color?

**Comment by escowles** [comment]
What about something like `dcterms:accessRights PUL#colorPDF` ?

**Comment by tpendragon** [comment]
Range is `A statement about the intellectual property rights (IPR) held in or over a Resource, a legal document giving official permission to do something with a resource, or a statement about access rights.` Seems odd.

**Comment by escowles** [comment]
If we're deciding whether someone can access the color PDF vs. grayscale vs. none based on copyright, then the "statement about access rights" seems like a good fit to me.  Though I admit I'm fuzzy on what the real use cases for restricting access or providing access to the color PDF are.
