### ISSUE TITLE
Labels not coming in on canvases

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#519]
E.g. In pudl0032/4223y : 

https://hydra-dev.princeton.edu/concern/scanned_resources/pg15bd892/manifest

Canvases have `label: "00000001.tif"`, where I'd expect `f. 1a`, `f. 1b`, etc.

**Comment by escowles** [comment]
I built a small object in Plum and looked at the `logical_order.order` hash , and found it did not contain the FileSet labels (just a `proxy` property mapping to the FileSet id.  So I think the issue here is that the ingest job needs to set the title of the FileSets as they are created.
