### ISSUE TITLE
Logical Structure not rendering in UV

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#547]
Not sure if it's not coming over, or what, but this item in dev:

https://hydra-dev.princeton.edu/concern/scanned_resources/sf2685136

has what I would want to be the page/canvas labels showing up in the UV's "Index". If you look in the Contents tab of the PUDL's viewer, it has two levels of structure:

http://pudl.princeton.edu/viewer.php?obj=tx31qh767#page/1/mode/1up

This is the relevant METS:

https://drive.google.com/open?id=0B4Wo5hgOEFY3Ri11eUpUYzgxRTQ

**Comment by tpendragon** [comment]
It seems to me like the page/canvas labels are right for this item, but the logical structure is most definitely wrong. (Missing Title Page/Preamble/Etc). Yes?

**Comment by jpstroop** [comment]
Yes.

**Comment by tpendragon** [comment]
Moving this discussion here.

Right now it pulls the logical structure from the physical structMap. Discussion in Slack says we should instead always pull from the logical map, and if it's not there then don't bother asserting logical order.

Does this mean the fixture structmaps are wrong, because it has nested information? @escowles?

**Comment by tpendragon** [comment]
Or is that needed for label names and we just need a fixture with a logical order?

**Comment by escowles** [comment]
I think we need to add better logical order examples, but the existing fixtures are probably good (they are lightly edited from real data, mostly just removing extra files).

**Comment by jpstroop** [comment]
The Islamic Mss (pudl0032) should all have both logical structure and physical labels.

**Comment by jpstroop** [comment]
I wonder if referring to it as 'logical order' is confusing things.
I don't *think* there are ever labels at the leaf `div`s in the Logical structure, and with only a few exceptions (bibles, which have physical structure we've agreed to collapse into labels), I think the Physical structure is only volumes at most, and otherwise flat. Order and labels should come from Physical if there are any `div`s beyond the root `div`, and otherwise from RelatedItems.

**Comment by tpendragon** [comment]
Updated version here: https://hydra-dev.princeton.edu/concern/scanned_resources/st74cq51f#?c=0&m=0&s=0&cv=0

Works?
