### ISSUE TITLE
Test many workers on lib-proc3

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#554]
Time sensitive...would be good to know if we need to order more soon. I will email proc machine users and let them know not to use it.

cc: @cwulfman @pmgreen @sdellis @eliotjordan @roelmoon

**Comment by tpendragon** [comment]
Leaving notes here for myself.

Will need to get Redis/Fedora/Solr/Postgres all open and talking to lib-proc3.

**Comment by jpstroop** [comment]
8080 is open to campus as of yesterday, fwiw
