### ISSUE TITLE
Can't update page order

### ISSUE THREAD

**Issue by flyingzumwalt** [pulibrary/plum#56]
In order for #9 to be complete, someone has to address projecthydra-labs/activefedora-aggregation#71

**Comment by flyingzumwalt** [comment]
FYI @terrellt @jpstroop

**Comment by flyingzumwalt** [comment]
Based on a comment by @jcoyne, it might not be possible to avoid loading all of the member objects.  That means you have to load **every page** in a book in order to update the page order within the book.

**Comment by terrellt** [comment]
It strikes me that the most efficient method may be to update the proxies and keep track of neighbors on movement, making the max number of updates 6. The danger is a bug causing a break in the links.

**Comment by jpstroop** [comment]
Duplicate of #9 ?
