### ISSUE TITLE
Store and index legacy PUDL identifier

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#561]
These are path based "identifiers" e.g. "pudl0001/4609321/s42" (with an arbitrary number of segments, but generally not more than four, and usually two) for objects and "pudl0001/4609321/s42/00000001" for images.

This will help us know what has been migrated as also deal with the rare case where someone remembers a collection or item based on it's PUDL number.

/cc @joycebcat

**Comment by jpstroop** [comment]
if the slashes make things weird for some reason we could escape them (`%20`)

**Comment by escowles** [comment]
This is already being done for objects, but not for files.

See: https://hydra-dev.princeton.edu/concern/scanned_resources/6q182k185 which includes "Replaces: pudl0032/440y"

Based on the comment, it sounds like this should also be done for FileSets too.

**Comment by jpstroop** [comment]
> Based on the comment, it sounds like this should also be done for FileSets too.

:+1:
