### ISSUE TITLE
structural MD feedback

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#563]
@tpendragon @jpstroop I did some physical and logical structure for the test object.  In general it was really straightforward and easy. (Actually a lot better than I was expecting!)  Here are some specific comments on the few not-so-great areas:

physical: Is there a way to change the label on group of images to something which doesn't include a number?  Maybe this doesn't matter.  I fixed the book then realized there were things leftover which still had an image number label (a few pages at the end and beginning).  I turned them into "page" by relabeling each separately.

physical: Having to click on the x to delete existing text before being able to type in new text is a nuisance.

logical: I can't read the image while I'm typing.  I can quickly look at a large enough version to get the data I need, but then I have to remember it all when I go to type it in.  Not a deal-breaker but not ideal.

logical: The indents for the different levels of structure are too subtle.  It was easy to get lost as to whether my new section was as deep as the last section or deeper.  I had some trouble creating new sections at the same level as the previous section, but I'm sure that will sort out with more practice.  Since I can't collapse and view from this interface, a color change or a deeper indent or something would be appreciated.

**Comment by joycebcat** [comment]
@tpendragon Hey, I realize you *can* collapse sections in the structure editor!

**Comment by joycebcat** [comment]
Playing around with this some more, the difficulty of telling what level you are in becomes a real problem.  I also can't seem to create a new section without embedding it deeper than I want to.  The button at the top for new section seems pointless--if I use it, it create a section at the top and then I have to try to drag it down to where I want to actually use it.  I'm having problems selecting a range of pages and dragging them into the right section.  If I collapse sections to make it easier to see where I am, they pop back open as soon as I do anything.

**Comment by tpendragon** [comment]
@joycebcat

1) You should be able to just not put a starting number in.
2) I think this is fixed now.
3) logical: Do you just need the thumbnails to be bigger?
4) logical: I think this is fixed now.
5) I think creating the sections is much clearer now, with better collapse/expand functionality, and they don't auto-expand anymore.

I'd like to break this ticket up into smaller tickets - one per issue. I think only #3 (can't read image while typing) is an issue, but I don't know the right solution. Can we create a new issue for that and close this?

**Comment by joycebcat** [comment]
@tpendragon Yes, we can close this and create separate tickets.  Two issues left I think.  #3 as you mentioned about reading image while typing.  I don't have a clear solution either but it deserves to stay as an issue.  The other thing is the ability to label images without including a number.  You say that I should be able to just not put a starting number in but doing so does nothing.  (I don't have time to create the two new tickets right now)

**Comment by tpendragon** [comment]
@joycebcat Thank you! Opened up #617 and #616. Closing this one.
