### ISSUE TITLE
When ingesting an item a derivative should be created which builds hOCR of the document via Tesseract and stores it

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#57]
https://github.com/meh/ruby-tesseract-ocr seems to be the most active.

Users doing ingest may need to set language for best results. Should this be in Hydra::Derivatives?

**Comment by terrellt** [comment]
Doesn't CC do this with Tika already?

**Comment by jpstroop** [comment]
Not from images I don't think, does it--I think it extracts text from document formats like Word, PDF, etc. I could be wrong, though. And we'd want Zones.

**Comment by terrellt** [comment]
There's a way to chain in Tesseract to Tika, but the documentation seems troublesome.

**Comment by tpendragon** [comment]
Scope for this ticket: When ingesting an item a derivative should be created which builds hOCR of the document via Tesseract and stores it. Useful: https://github.com/meh/ruby-tesseract-ocr#hocr

**Comment by jpstroop** [comment]
Here's some sample HOCR https://gist.github.com/jpstroop/abc27a5a87e2268fc184

**Comment by tpendragon** [comment]
To close this, what needs to be supported:

1) Searching in the catalog returns full text results (probably with highlighting)
2) Annotation lists are linked to each canvas in the manifest, with the full text as annotations.

**Comment by jpstroop** [comment]
UI should support changing the language and the `pagesegmode`

```
pagesegmode values are:
  0 = Orientation and script detection (OSD) only.
  1 = Automatic page segmentation with OSD.
  2 = Automatic page segmentation, but no OSD, or OCR
  3 = Fully automatic page segmentation, but no OSD. (Default)
  4 = Assume a single column of text of variable sizes.
  5 = Assume a single uniform block of vertically aligned text.
  6 = Assume a single uniform block of text.
  7 = Treat the image as a single text line.
  8 = Treat the image as a single word.
  9 = Treat the image as a single word in a circle.
  10 = Treat the image as a single character.
```

**Comment by tpendragon** [comment]
@jpstroop Do you have the file you ran that on? Looking at ruby-tesseract-ocr and seeing if we can avoid shelling out.

**Comment by tpendragon** [comment]
https://github.com/meh/ruby-tesseract-ocr/issues/50 Ruby library doesn't support Tesseract 3.04

**Comment by jpstroop** [comment]
@tpendragon files in slack

**Comment by tpendragon** [comment]
With the gem it looks like you can set the page mode with `page_segmentation_mode = 4`

**Comment by tpendragon** [comment]
Split out #381, #382, #383, #384, #385, #386 from this issue. This issue is now just "run tesseract derivatives and store them"
