### ISSUE TITLE
Structure: How to add a section beneath a section?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#570]
Probably easiest to watch me fumble (I pulled this from my attempts to make a screencast last night): https://vimeo.com/165425914

**Comment by tpendragon** [comment]
@jpstroop You have to do it when it's not compressed.

**Comment by tpendragon** [comment]
@jpstroop https://vimeo.com/165492822

**Comment by jpstroop** [comment]
But how do I add Chapter 2? (A sibling of Chapter 1)
