### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#571]
@kevinreiss pointed out that hydra-dev is showing up in [Google results](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=princeton+blacklight). Fine since you can do anything w/o logging in, but we should probably try to keep it out to whatever extent we can.

Do we want to reconsider putting it behind the firewall? It's a massive pain for demos, but throwing it out there....

**Comment by escowles** [comment]
+1 to robots.txt and leaving it open until it's a problem.
