### ISSUE TITLE
structural label is "stuck" at one level

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#574]
I was testing with the "Example object for Joyce".  I created all the labels, then I was checking that they were created at the correct level and dragging them up to where they belonged (because the way I'm creating them they seem to always want to nest).  One of the labels -- View on the Delaware -- is "stuck".  I can't drag it up to the same level at the Boston Lighthouse label.

**Comment by tpendragon** [comment]
:+1: Seeing this too. Strange - only way I could find to do it was to drag View on the Delaware above Boston Lighthouse, drop it, then move it below it.

**Comment by joycebcat** [comment]
I'm having similar problems with another title I'm playing with.

**Comment by tpendragon** [comment]
I'm hoping this was fixed with #511, but we're having to wipe everything for the solr 6 upgrade, so we'll have to wait and see.
