### ISSUE TITLE
`metadata` in Manifest not showing separate languages/scripts

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#577]
See: https://hydra-dev.princeton.edu/concern/scanned_resources/79407x291/manifest

```javascript
{
   "label": "Creator",
   "value": [
      "Ibn Quṭlūbughā, al-Qāsim ibn ʻAbd Allāh, 1399 or 1400-1474 or 1475",
      "ابن قطلوبغا، القاسم بن عبد الله"
   ]
},
```

`"value"` should be a list of hashes with `@lang`, `@value`, etc.

**Comment by tpendragon** [comment]
There was a bug in AT that turned off being able to cast to literals - that's fixed in AT now, but I'd have to get AF caught up to the new Relation changes in order to get it in. So in the meantime I'm pushing this issue back to work on other things.

**Comment by tpendragon** [comment]
Some more info here: `get_values(:author, literal: true)` works, but manifests are built from the solr record, and the record's metadata only indexes strings - not the literals (with language tags), because that would require multiple fields for one "value".
