### ISSUE TITLE
Saving... not coming back on File Manager

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#578]
Several times at the end of last week and over the weekend, after bulk-labeling and setting direction etc. on https://hydra-dev.princeton.edu/concern/scanned_resources/79407x291 I waited for ~5-10 minutes for the object to save. That seems abnormally long, right (this object has 250 images)?

I eventually reloaded the page, and in all but one case my changes were there.

Not sure how to recreate other than try doing same on a large object (please keep this one intact for me for the IIIF week).

**Comment by jpstroop** [comment]
PS, I thought maybe it was a glitchy connection at home, but it also happened a few times on campus on Saturday.

**Comment by tpendragon** [comment]
#607 should help diagnose this. Old items in Plum probably aren't good to test it with - there seem to be permission problems from switching to the new ACL strategy.
