### ISSUE TITLE
Index data alignment for rtl languages

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#580]
We have a lot of objects in the pudl which have logical structure only in non-roman script running rtl.  In the index display of sections these are left justified.  Example: Majmu min al-rasail.  Not a deal breaker, but not elegant.

**Comment by tpendragon** [comment]
@jpstroop Something to bring up with Tom regarding our UV tickets?

**Comment by jpstroop** [comment]
It was definitely on the list at one point, but may have fallen off.

**Comment by jpstroop** [comment]
https://github.com/UniversalViewer/universalviewer/issues/299

**Comment by tpendragon** [comment]
Closed in favor of https://github.com/pulibrary/plum/issues/1221
