### ISSUE TITLE
Choice of image

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#581]
See http://iiif.io/api/presentation/2.1/#choice-of-alternative-resources

We have this use case--especially for the bibles and some books from the GA collection.

UV supports it and will give you a dropdown. Can we get this in the file manager somehow? I could imagine a drop down labeled "Alternate For:" that lists the other files by label, starting with the previous image.

**Comment by tpendragon** [comment]
This actually looks like the perfect mapping for a Work with multiple image FileSets. We'd need the UI and parts in the stack to do that though.

**Comment by jpstroop** [comment]
Heh, yeah. I see that.

**Comment by escowles** [comment]
Can we write up this use case?  I've tried to encourage discussion of the scenarios where people would have multiple FileSets attached to an Object, but that hasn't been very productive so far.  So documenting our use case could really help here.

**Comment by jpstroop** [comment]
We have two: lace overlays on pages (so an image w/ the overlay and an image w/o), and images of a page that was bookmarked (we have an image with the bookmark, and an image w/o).
