### ISSUE TITLE
Add layer to manifest for all annotation lists in sequence.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#598]

**Comment by tpendragon** [comment]
I'm not sure this is useful for indexing. What MIGHT be useful is something like this in `rendering`:

```
{
@id: "http://hydra-dev.princeton.edu/concern/scanned_resources/1/text",
format: "text/plain",
label: "Download raw text"
}
```

which we can then pull and stuff in solr. Thoughts @jpstroop?

**Comment by jpstroop** [comment]
Depends on our long-term goals I suppose. If we want hit-highlighting a'la the IIIF search API (which is think is what is expected) we're going to need coordinates, no? 

Also feels like a slight hack of [`rendering`](http://iiif.io/api/presentation/2.1/#rendering). It's readable by humans but still really meant for machines....not sure how I feel about it.

**Comment by tpendragon** [comment]
We get coordinates from the annotation lists, which will be good for hit highlighting. Layers don't embed the full annotation lists in them though, they just have references to them - which means to index the full text OCR from a manifest with 600 canvases it would take 600 requests.

**Comment by tpendragon** [comment]
Should clarify, for the `rendering` I'd just put the text part of the HOCR in there, not the coords.

**Comment by jpstroop** [comment]
So what's the flow for hit-highlighting on an image if the coords aren't Solr?

**Comment by tpendragon** [comment]
Ive never figured out solr searching hocr, despite like 6 months of trying. I always brute forced it.

**Comment by tpendragon** [comment]
Maybe a solr document per annotation?

**Comment by jpstroop** [comment]
Probably. Though if you wanted auto complete by word wouldn't it....gulp...be at the word level?

**Comment by jpstroop** [comment]
I dunno...we've definitely assumed in the spec that, e.g. 600 requests wouldn't be a problem. Maybe that needs rethinking.

**Comment by tpendragon** [comment]
> Though if you wanted auto complete by word wouldn't it....gulp...be at the word level?

What does auto complete mean in the context of searching? This is probably a different issue, we're not doing IIIF Search yet, yeah?

**Comment by jpstroop** [comment]
So...UV will give us auto complete per-word if it's configured. Cicognara folks are expecting to get to the page, presumably (though I guess we didn't say it) with the word highlighted.

**Comment by tpendragon** [comment]
We should have a discussion about what searching an hOCR document means, because there's a couple problems:

1. Solr just searches a document and returns the text back, as you gave it, with the matches surrounded by a tag. It doesn't return any offset information, and it can't search different text than it surrounds.
2. You can't really use multiple solr documents for the granularity you want, because it makes phrase searching impossible. If the search "what does the dog say" goes between lines 1/2, it would never be returned.

Current experiment I'd never thought of would look something like this:

1. Strip HTML tags from hOCR, but not wholesale. As you strip them, keep track of how the location of each word in the hOCR maps to the stripped version (this..might get complicated. Nested tags means you'd need some sort of algorithm that goes by depth, and starting from deepest..). Put it in a big hash or something.
2. Put the stripped HOCR (now it's just text) into a solr field, and run highlighting on it. Configure highlighter to return the entire value, but with <em> tags surrounding it. (THIS WILL BE A PROBLEM FOR BIG OCR. Maybe separate this by page, if phrase highlighting cross-page isn't important?)
3. Count where the em tags happen, pull up the hash you stored from before, and see where that string position compares to the hOCR document's string position.
4. Return the annotations appropriately.
5. Write a really cool article.

**Comment by tpendragon** [comment]
PS, we should ask how @tomcrane does it, when we get there. :)

**Comment by jpstroop** [comment]
That's what I was going to say.

**Comment by jpstroop** [comment]
But also:

> You can't really use multiple solr documents for the granularity you want, because it makes phrase searching impossible. If the search "what does the dog say" goes between lines 1/2, it would never be returned.

That's been discussed in the context of the search API...we're staying silent and basically saying "think of this as ctrl+f in the browser. the line/para/page wrapping is less of a concern with annotations created by humans...so there is definitely a disconnect there.

For the rest...I'm tired :sleepy: let's catch up on Monday.

**Comment by escowles** [comment]
I dunno -- that sounds really complicated and hard to get right.  Couldn't we just have a multi-pass approach:

Pass 1: Index the whole book (or whatever) in one big text blob.  Seaching in Solr gets you to the book.
Pass 2: Index each page separately.  Do a second search to figure out which pages have highlights on them.
Pass 3: Pull the hOCR for the page and figure out where the highlights are.

**Comment by tpendragon** [comment]
> Pass 3: Pull the hOCR for the page and figure out where the highlights are.

Yes, but it'd be just as inefficient as if solr was never involved at all. (Well, maybe a bit more if solr could get you the pages involved...again though, page boundaries might be a problem for phrases). All you'd get there from solr is stemming, you'd still have to parse the OCR document looking for matching text.

**Comment by escowles** [comment]
Fair point — maybe pass 2 would get you highlights to figure out where on the page your terms were.  Though that sounds like it's the same as your proposal, but on a smaller scale.

**Comment by tpendragon** [comment]
The last time I did this I totally gave up and wrote a brute force phrase searcher for hOCR, solely because of these problems. It worked, but you'd have to be okay with 20-40 seconds to get a result back on large books.

**Comment by tpendragon** [comment]
Oh, for completeness - this is super easy if we give up phrase searching. If "this dog runs" just highlights every instance of "this" and "dog" and "runs", we could do that super fast.

**Comment by jpstroop** [comment]
Not sure if this is helpful, but bookmarking for later: https://blogs.loc.gov/digitalpreservation/2014/08/making-scanned-content-accessible-using-full-text-search-and-ocr/

**Comment by tpendragon** [comment]
Yup, looked at that when I did OD's. No phrase support, or at least I don't see how they'd do it. They effectively use @escowles' method.

**Comment by escowles** [comment]
I think the field collapsing in that article might be what we should be doing instead of the join-and-suppress approach we're taking now.  I think that's worth investigating to see if we can get Solr to join things for us and calculate the combined relevance.

Either way, I think using a multi-pass process will make our lives easier, because finding works and pages won't need to use the highlights at all (since we're only showing highlights at the page level, right?).

At the page level, I think Trey's approach looks like:

1. Transform the OCR to a list of span.ocrx_word, and make a list of the bounding boxes, and index that.
2. Transform the OCR to plaintext and index that.
3. Get highlights from the plaintext field (configured to return the entire field) and count the position of each highlighted word.
4. Look up the bounding boxes from the bbox list and return those.

That is starting to sound reasonable "highlight service" to me.

**Comment by tpendragon** [comment]
I wonder if field collapsing is the solution to searching Multi Volume Works too.

**Comment by tpendragon** [comment]
So what we're going to do is allow for an expanded version of layers which embeds AnnotationLists.

**Comment by tpendragon** [comment]
Add a parameter to expand the layer so that it can embed all the annotation lists.
