### ISSUE TITLE
Assign default labels for pages on ingest

### ISSUE THREAD

**Issue by terrellt** [pulibrary/plum#6]

**Comment by terrellt** [comment]
Where do the default labels come from?

**Comment by tampakis** [comment]
I think they come from the [generic_file_actor](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/curation_concerns/generic_file_actor.rb#L63-L64).

**Comment by tampakis** [comment]
Unless if your question is about our actual data...

**Comment by flyingzumwalt** [comment]
Current default: uses the filename of the uploaded image.
