### ISSUE TITLE
Font for Arabic

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#632]
PUDL uses `font-family: 'Times New Roman', 'Arial Unicode MS', serif;`

**Comment by eliotjordan** [comment]
Is this closed by #670?

**Comment by eliotjordan** [comment]
Maybe there are still issues with Arabic fonts for PDF generation?

**Comment by tpendragon** [comment]
This is arabic fonts in the page, #670 was for the PDF I think.

**Comment by escowles** [comment]
Yes, #670 is for the PDF fonts, this ticket is for the in-browser display.
