### ISSUE TITLE
How to manage a bad JP2?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#643]
Image 7 here:

https://hydra-dev.princeton.edu/concern/container/nz805z907/scanned_resources/vt150j54x

is probably just a bad JP2 (info.json seems to think it's much smaller).

https://hydra-dev.princeton.edu/concern/file_sets/0c483j488

Do we have a way to replace a derivative if we need to?

**Comment by jpstroop** [comment]
Oh...or it be a NOID clash in the info cache on the image server?

**Comment by escowles** [comment]
I don't think it's a NOID clash — I removed all of the old JP2s and cleared the Loris cache on libimages1 last night.

That said, it would be good to have a way to regenerate derivatives.  Right now, you'd have to replace the image to trigger that, or hand-launch it from the console.

**Comment by escowles** [comment]
Related to #499
