### ISSUE TITLE
Display placeholder for FileSets before thumbnail is available?

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#645]
Since we want to prioritize ingesting into Fedora over characterization/derivatives, FileSets will be present for a while before a thumbnail is available.  Do we want to show a placeholder if the thumbnail isn't ready?

**Comment by tpendragon** [comment]
Do we have a way to know if the placeholder is ready yet?

**Comment by escowles** [comment]
Isn't there a standard way to have a fallback to display for an image tag if the main src doesn't work?
