### ISSUE TITLE
PDFs can't be generated for UTF-8 characters.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#650]

**Comment by escowles** [comment]
This is related to #632.  We need to add a font that supports the UTF-8 characters used in metadata, and use it in the Prawn document:

```
prawn_document.font(Rails.root.join("app/assets/fonts/font.ttf"))
```

**Comment by escowles** [comment]
I've futzed around with various fonts and Prawn options — I was able to get Arabic working, but not Chinese.

I started looking around at other options, and found a PDF library called [wisepdf](https://github.com/igor-alexandrov/wisepdf) that relies on [wkhtmltopdf](http://wkhtmltopdf.org/) for converting HTML to PDF.  I had to manually download and install wkhtmltopdf, but a quick test worked for Arabic and Chinese with no font configuration or anything.  So I think it might be better to just use wisepdf instead.

**Comment by jpstroop** [comment]
Is it a font issue? I seem to remember having to install some fonts on the finding aids server to get certain characters to show up properly w/ FOP. 

See step 7 here:

https://github.com/pulibrary/dev-docs/blob/master/source/apps/exist_for_pulfa_and_pudl/index.md#enable-the-fop-module

Fonts here: https://github.com/pulibrary/pulfa/tree/development/fop-fonts

**Comment by jpstroop** [comment]
Oh, sorry, you said it was as font issue above.

**Comment by escowles** [comment]
Yes, and it's a frustrating font issue — fonts that work fine in my browser and other apps don't work when I try to use them with Prawn.

**Comment by tpendragon** [comment]
I wonder if it's because browsers know to fall back?
