### ISSUE TITLE
thumbnails getting squashed/stretched in file manager

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#653]
See: 
https://hydra-dev.princeton.edu/concern/scanned_resources/b5644r64n/file_manager

around image 9, look at the aspect ratio of the thumbnail vs. the zoom view

**Comment by tpendragon** [comment]
@jpstroop Screenshot? They look fine to me, and comparing the width/height of the thumbnail to what the image server outputs shows both with a 0.56 w/h ratio.

**Comment by jpstroop** [comment]
Huh. They're fine for me now too...I cleared my cache a few minutes ago. Maybe that was it.
