### ISSUE TITLE
OSd zoom on 2nd and greater image is jerky

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#654]
The zoom is always smooth, after that the the zoom into addition thumbnails is jerky.  The message

> Hash Openseadragon1 has already been used.

appears in the JS console for each additional zoom. Might be related?

**Comment by tpendragon** [comment]
@jpstroop Is this in UV? Or do you mean the modal pop ups for things like the file manager?

**Comment by jpstroop** [comment]
the modal pop ups for things like the file manager
