### ISSUE TITLE
Remove Attach a File

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#669]

**Comment by tpendragon** [comment]
Realized we have a feature spec for this. Do we still want to keep the "attach one file set" page?

**Comment by jpstroop** [comment]
This is on the #create page? The only use case I can think of is that we have collections that use thumbnails that aren't images in the collection. Would we do that here or in Pom?

**Comment by tpendragon** [comment]
This is on the show page.

**Comment by jpstroop** [comment]
I see. Can't think of a use.
