### ISSUE TITLE
Do Scanned Maps fit?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#67]
Given that:
 * The source metadata lives in Voyager at MARC
 * The delivery mechanism isn't the repo and could/should be Blacklight (perhaps GeoBlacklight and OrangeLight, which makes this similar to Plum's emphasis on reuse/embedding).
 * IIIFification is a requirement (correct?)
 * Model behaviors are similar (names are wrong)
 * Workflow requirements _seem_ similiar

`ScannedBook` could be `ScannedResource` and the notion of "pages" could be abstracted a bit more, as "surfaces".

I think this could work.

@eliotjordan and @terrellt could we do a hangout to discuss this on Monday?

**Comment by terrellt** [comment]
Yes. Rename ScannedBook to ScannedResource.
