### ISSUE TITLE
Buttons showing up on visibility text

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#671]
Uhh....

<img width="1188" alt="screen shot 2016-06-13 at 11 02 00 am" src="https://cloud.githubusercontent.com/assets/999701/16003849/9969d152-3156-11e6-903c-ca92e2859735.png">

**Comment by escowles** [comment]
This happen in stock CurationConcerns too.

**Comment by escowles** [comment]
I didn't even notice that the buttons were just inline labels until I got into looking at the views.  Luckily, there was already a CC issue for a redesign of the whole thing to avoid the wall of text altogether, so I'll just work that issue: https://github.com/projecthydra/curation_concerns/issues/824
