### ISSUE TITLE
Paging buttons out of line in UV

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#679]
https://hydra-dev.princeton.edu/concern/scanned_resources/8p58pd36k

![image](https://cloud.githubusercontent.com/assets/999701/16424243/60da57de-3d2d-11e6-8434-1f5994aaa7ab.png)

**Comment by tpendragon** [comment]
Just the dropdown is funny now, yeah?
![screen shot 2016-08-18 at 2 21 48 pm](https://cloud.githubusercontent.com/assets/2806645/17791260/27ef509c-654f-11e6-98c5-98df0a3630a1.png)

**Comment by jpstroop** [comment]
yeah :+1:
