### ISSUE TITLE
If ARKs point to Orangelight, how do we link from that view to collection(s) in Pom?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#694]

**Comment by jpstroop** [comment]
*   Pom dumps a map (`ark : [slug, slug]`) that Orangelight can use during indexing?
  *  On the fly?

**Comment by escowles** [comment]
I like the idea of doing this on the fly: javascript to query pom for collections that contain the object and display links to them.

**Comment by jpstroop** [comment]
:+1:  If the ARK is in the record in Orangelight, and we put it in [`rendering`](http://iiif.io/api/presentation/2.1/#rendering) in our Manifests, that could be used to query Pom.

**Comment by jpstroop** [comment]
My suggestion above isn't a good one (we should do that, but not leverage it to solve this problem)

Seems like solving this with an ark resolver in Pom similar to #1092 is the way to go.

**Comment by tpendragon** [comment]
Closed in favor of https://github.com/pulibrary/orangelight/issues/869 and https://github.com/pulibrary/pomegranate/issues/263
