### ISSUE TITLE
Email people w/ Roles

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#719]
Ask them to sign up but not do anything after #718

**Comment by tpendragon** [comment]
@escowles I thought we did this a long time ago. Here: https://github.com/pulibrary/plum/blob/master/app/models/concerns/common_metadata.rb#L38

**Comment by tpendragon** [comment]
@escowles I thought we did this a long time ago. Here: https://github.com/pulibrary/plum/blob/master/app/models/concerns/common_metadata.rb#L38

**Comment by escowles** [comment]
I think this ticket was for coordinating testing of that functionality — asking the people with various roles to sign up for accounts so we can assign them roles, then move objects through the workflow and make sure they actually get the email notifications.

**Comment by tpendragon** [comment]
Gotcha.

**Comment by jpstroop** [comment]
@escowles @eliotjordan Any relation to Cipity workflows / CC 2.0?

**Comment by eliotjordan** [comment]
@jpstroop At this point users have to be manually assigned workflow roles using the admin dashboard. So that's an extra step beyond assigning Plum roles.

**Comment by jpstroop** [comment]
OK, just checking. Thanks.
