### ISSUE TITLE
There should be a way to select lossless compression when uploading a book

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#72]
An I should be able to replace the derivative JP2s with a new set using a different recipe.

A refinement of #26, based on [this comment](https://github.com/pulibrary/plum/issues/26#issuecomment-138917188) and [this comment](https://github.com/pulibrary/plum/issues/26#issuecomment-138764638).

**Comment by tpendragon** [comment]
@roelmoon Are there us cases for more JP2 recipes than four? "Grayscale, Color, Lossless Color, Lossless Grayscale"? If not, can we change this ticket to read "There should be a way to select lossless compression when uploading a book"?

**Comment by roelmoon** [comment]
Currently there are only 4 use cases for JP2 creation.

Derivative creation is a blind process, and the catalyst for creating a lossless version was that compression artifacts weren’t noticed until after images were in production. I know that we will have the ability to add/delete or reorder images prior to going into production. Will be a way to re-ingest images with lossless compression after compressed images are in production?

That question aside, yes, we should have the ability to choose on ingest whether or not to use compression.

Roel

On Oct 27, 2015, at 1:14 PM, Trey Pendragon <notifications@github.com<mailto:notifications@github.com>> wrote:


@roelmoon<https://github.com/roelmoon> Are there us cases for more JP2 recipes than four? "Grayscale, Color, Lossless Color, Lossless Grayscale"? If not, can we change this ticket to read "There should be a way to select lossless compression when uploading a book"?

**Comment by tpendragon** [comment]
What the workflow is like post marking as complete is up in the air I think, but before that you'd certainly be able to delete the old image, upload a new one, and move it into the right place.

**Comment by tpendragon** [comment]
@jpstroop @roelmoon When possible can one of you post the JP2 recipes that represent lossless compression?

**Comment by jpstroop** [comment]
I think these are the correct recipes for lossless:

Color:

-rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=yes Clevels=7 Cblk=\{64,64\} -jp2_space sRGB Cuse_sop=yes Cuse_eph=yes Corder=RLCP ORGgen_plt=yes ORGtparts=R  Stiles=\{1024,1024\} -double_buffering 10 -num_threads 4 -no_weights -quiet

Gray:

-rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=yes Clevels=7 Cblk=\{64,64\} -jp2_space sLUM Cuse_sop=yes Cuse_eph=yes Corder=RLCP ORGgen_plt=yes ORGtparts=R  Stiles=\{1024,1024\} -double_buffering 10 -num_threads 4 -no_weights -quiet

**Comment by roelmoon** [comment]
Those are recipes for compressed, 10:1. Only difference is a slight modification in the “rate”. Lossless recipes are:

Color:
-rate -,2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=yes Clevels=7 Cblk=\{64,64\} -jp2_space sRGB Cuse_sop=yes Cuse_eph=yes Corder=RLCP ORGgen_plt=yes ORGtparts=R Stiles=\{1024,1024\} -double_buffering 10 -num_threads 4 -no_weights -quiet

Gray:
-rate -,2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=yes Clevels=7 Cblk=\{64,64\} -jp2_space sLUM Cuse_sop=yes Cuse_eph=yes Corder=RLCP ORGgen_plt=yes ORGtparts=R Stiles=\{1024,1024\} -double_buffering 10 -num_threads 4 -no_weights -quiet

Roel

On Oct 28, 2015, at 11:15 AM, Jon Stroop <notifications@github.com<mailto:notifications@github.com>> wrote:


I think these are the correct recipes for lossless:

Color:

-rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=yes Clevels=7 Cblk={64,64} -jp2_space sRGB Cuse_sop=yes Cuse_eph=yes Corder=RLCP ORGgen_plt=yes ORGtparts=R Stiles={1024,1024} -double_buffering 10 -num_threads 4 -no_weights -quiet

Gray:

-rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=yes Clevels=7 Cblk={64,64} -jp2_space sLUM Cuse_sop=yes Cuse_eph=yes Corder=RLCP ORGgen_plt=yes ORGtparts=R Stiles={1024,1024} -double_buffering 10 -num_threads 4 -no_weights -quiet

**Comment by jpstroop** [comment]
Oops, right, missed the "-".

**Comment by jpstroop** [comment]
@rmoon Do you think we could get away with just always doing lossless?

**Comment by rmoon** [comment]
For brittle books or everything?

**Comment by jpstroop** [comment]
Everything

**Comment by rmoon** [comment]
Maybe performance issues? None once the object is cached, I assume. I guess longer term, storage space, images will be 4-5 times larger.

**Comment by jpstroop** [comment]
Wow, 4-5 times? That's more than I expected. I don't feel too worried about performance issues because the uncompressed stuff we've done for Julie has always been fine. But that storage is going to add up, so I think this should still be something we support.

**Comment by tpendragon** [comment]
Do we have some items that we know this is a problem for?

**Comment by rmoon** [comment]
Yes, there are some Graphic arts items with very fine engraving detail that gets mashed with even the slightest lossy compression. Used lossless jp2 for those.
