### ISSUE TITLE
Ingest Scheide collection

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#720]
Fresh tarball https://drive.google.com/drive/u/1/folders/0B4Wo5hgOEFY3ZlZGUU5OS3FIbDA

**Comment by escowles** [comment]
I am going to ingest a few objects in dev to test #726 (and get a rough estimate of how long it'll take to ingest all of Scheide.

**Comment by jpstroop** [comment]
:+1:

**Comment by escowles** [comment]
So far, the ingest has processed 470 files in 1h47m — about 14s/file.  At this rate, it'll take about 28 hours to process the entire Scheide collection (~7400 files).

The background workers look like they are keeping pace with the ingest, running on the same machine as ingest.  So I would expect the ingest in production to go a little faster with the separate worker machine.

**Comment by jpstroop** [comment]
Faster than weeks!

**Comment by jpstroop** [comment]
East Asian is about 120K files, to there's that...

**Comment by jpstroop** [comment]
Wonder if it's worth trying to to more than one at a time?

**Comment by tpendragon** [comment]
Wouldn't be any faster except on production.

**Comment by escowles** [comment]
http://plum.princeton.edu/catalog?f%5Bmember_of_collections_ssim%5D%5B%5D=Scheide+Library+%3A+Fifteenth-Century+Printing

**Comment by jpstroop** [comment]
Moved to tracking in google sheets
