### ISSUE TITLE
Dump fresh collections file

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#722]

**Comment by jpstroop** [comment]
See: https://gist.github.com/jpstroop/25d74df145aa286028b39c2ef82783b6

**Comment by jpstroop** [comment]
OK, https://gist.github.com/jpstroop/25d74df145aa286028b39c2ef82783b6#file-pud_collections-json is up to date

**Comment by escowles** [comment]
👍  — I've added `pudl_collections.json` file to Plum's config directory in #726
