### ISSUE TITLE
Error: undefined method `xpath' for nil:NilClass

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#739]
When ingesting, we saw a couple of records have this error, when trying to get the label for a file.  See https://github.com/pulibrary/plum/blob/master/app/models/concerns/mets_structure.rb#L13

**Comment by jpstroop** [comment]
Do you have a sample record ID?

**Comment by jpstroop** [comment]
Closed by 08c6e33de97ad0fd9912c480f8e52d0b09441445
