### ISSUE TITLE
Deleted First Volume flash message stuck

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#744]
I can't get this out of the top of my window:

![image](https://cloud.githubusercontent.com/assets/999701/18927722/1508fc56-858b-11e6-940b-482e83ee451a.png)

which is especially weird since I haven't deleted anything.

**Comment by escowles** [comment]
I saw that earlier with a different flash message (Logged in from CAS) — it went away eventually.

**Comment by jpstroop** [comment]
Still an issue?

**Comment by tpendragon** [comment]
So much has changed. Closing this until we see it again.
