### ISSUE TITLE
UI stretching thumbnails

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#745]
![](https://libimages1.princeton.edu/loris/plum_prod/pq%2Fv3%2F3r%2Fw6%2F5p-intermediate_file.jp2/full/!200,150/0/default.jpg)

becomes:

![image](https://cloud.githubusercontent.com/assets/999701/18997915/7d401424-8704-11e6-9cba-dc33b8329a66.png)

**Comment by tpendragon** [comment]
The original picture isn't loading. I'm not seeing stretching on that record - it really is a long  skinny one.

**Comment by jpstroop** [comment]
Still the case. It's long and skinny, but I think something with the CSS is causing the browser to upsample the thumbnail. [Image is 52 x 150px](https://libimages1.princeton.edu/loris/plum_prod/p4%2Fq7%2F7g%2Fm3%2F5x-intermediate_file.jp2/full/!200,150/0/default.jpg) but its getting stretched to 121x350.

Will show up with this query: http://plum.princeton.edu/catalog?utf8=%E2%9C%93&q=ars

**Comment by tpendragon** [comment]
This looks good to all of us. Can you check again, @jpstroop, and then close?
