### ISSUE TITLE
Rename ScannedBook to ScannedResource.

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#75]
See #67

**Comment by escowles** [comment]
Out of curiosity, is there anything specific to *scanned* resources?  As long as we're renaming, do we want to go even broader?

**Comment by jpstroop** [comment]
What did you have in mind? I'm open to ideas. What would be broader? DigitalThing? :wink:

**Comment by jpstroop** [comment]
Oh, noticed your emphasis on "scanned". Is that what you're questioning?

**Comment by jpstroop** [comment]
I don't think I'd want to go w/ e.g. just "Resource". DigitizedResource?

**Comment by escowles** [comment]
Yes, I'm mostly thinking of e.g., born digital materials. DigitzedResource seems better to me -- more neutral.

**Comment by tpendragon** [comment]
:+1: DigitizedResource

**Comment by jpstroop** [comment]
:ok_hand: 

Born digital. Yeah, about that....

**Comment by jpstroop** [comment]
I guess DigitizedResource vs. DigitalResource is a nice distinction.

**Comment by escowles** [comment]
I can see the distinction -- but would be say something shouldn't go in Plum because it was born digital instead of digitized?  Is there some other aspect of the resources that defined the scope here, like UploadedResource?

**Comment by jpstroop** [comment]
I think whether or not born digital stuff winds up in Plum os an open question. Workflow, metadata, and delivery requirements--including integrations with other tools like ASpace, DPN, etc. might make the whole thing different enough that it warrants a separate project.

Either way, I think it's a safe bet that Digitized vs [Born]Digital is a distinction we'll want to make.
