### ISSUE TITLE
Thumbnail selection partial showing in /edit

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#767]
E.g.: http://lib-plum1.princeton.edu/concern/scanned_resources/prn301141f/edit

![image](https://cloud.githubusercontent.com/assets/999701/19433406/8dc875de-942e-11e6-92a5-b56f95051585.png)

**Comment by tampakis** [comment]
Do we want to remove this?

**Comment by tpendragon** [comment]
Yeah, the file manager handles this now.
