### ISSUE TITLE
Extracting image width/height from FITS isn't working

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#775]
We should extract image width/height from FITS and store it as properties on the File and/or FileSet.  We should use these instead of hitting the image server when building manifests.

**Comment by jpstroop** [comment]
Confirmed this tailing the log on the image server--every `info.json` is hit every time a manifest is serialized. :sweat:

**Comment by tpendragon** [comment]
This only works with FITS 0.8.5, and we had a later version on lib-proc4. Fixed on the server, and there's a PR in our ansible scripts.
