### ISSUE TITLE
Faster characterization

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#776]
Running FITS takes a very long time (up to 80% of the time to ingest a TIFF is spent doing characterization).  Explore alternatives such as:
- Running JHove standalone
- Running a lightweight characterization service first (e.g., ImageMagick's identify), and then running FITS on a low-priority queue

**Comment by jpstroop** [comment]
Whether JHOVE or full-blown FITS, running the characterization as a service so that we're not spinning up the JVM every time would probably give us a good boost.

**Comment by escowles** [comment]
I think this issue is mostly resolved with https://github.com/ucsdlib/ansible-role-fits/pull/2 — disabling Tika/Tesseract has improved performance, now averaging about 10 seconds per file.

Running a FITS/JHOVE service might be a small improvement on that, however, and I agree it's worth looking into.
