### ISSUE TITLE
Role management form improvement

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#786]
To add a user to a role now, you have to type in their username.  We should have a menu or list of existing users who aren't in the role instead.

**Comment by jpstroop** [comment]
@escowles @eliotjordan Does the work update to the Sipity workflow have any bearing on this?

**Comment by eliotjordan** [comment]
Esmé and I were chatting about this yesterday. Sipity adds another set of roles: "workflow roles". At this point they are seperate from the roles we use in Plum. It would be nice in the future to figure out how to integrate these.

![screenshot 2017-01-06 09 21 23](https://cloud.githubusercontent.com/assets/784196/21722282/884f79a6-d3f1-11e6-9e1c-60106bf9e59b.png)

As to the main point of the issue, I think we might be able to do this with a custom addition to the new admin dashboard.
