### ISSUE TITLE
Multi volume object index

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#787]
The index for a "scanned resource" shows only the volumes regardless of what volume you are displaying.  The logical structure for the individual volumes is lost.  Example: Clarissa

**Comment by tpendragon** [comment]
@joycebcat I'm a little confused about what you mean here - could you clarify what you're not seeing that you would expect to?

**Comment by tpendragon** [comment]
Not sure if this is what the ticket is about, but it does look like some of the logical orders for "Clarissa" didn't get moved over - ping @escowles.

**Comment by escowles** [comment]
I think there isn't any structure inside the volumes, so the structMap just looks like:

structMap @TYPE="Physical"
  div @TYPE="MultiVolumeSet"
    div @TYPE="BoundVolume" @LABEL="01"
      page1
      page2
      etc.
    div @TYPE="BoundVolume" @LABEL="02"
      page1
      page2
      etc.

So since there's no structure inside the volumes, the flat list of volumes is all we get.  And since the volume titles are just "01", "02", etc., then that's all we have.

**Comment by tpendragon** [comment]
I'm not sure that's the case for Clarissa. Unless I'm reading the METS file wrong (likely!) there's entries like this:

```xml
<mets:div ID="i0p7p" LABEL="postscript" TYPE="Section">
<mets:div ID="u9dlk" ORDER="431" TYPE="LogicalMember">
<mets:fptr FILEID="pltl7"/>
</mets:div>
<mets:div ID="g6afz" ORDER="432" TYPE="LogicalMember">
<mets:fptr FILEID="reucz"/>
</mets:div>
<mets:div ID="tlsyz" ORDER="433" TYPE="LogicalMember">
<mets:fptr FILEID="u5vxb"/>
</mets:div>
<mets:div ID="ml994" ORDER="434" TYPE="LogicalMember">
<mets:fptr FILEID="jk1mc"/>
</mets:div>
<mets:div ID="gctub" ORDER="435" TYPE="LogicalMember">
<mets:fptr FILEID="d45kv"/>
</mets:div>
<mets:div ID="fna74" ORDER="436" TYPE="LogicalMember">
<mets:fptr FILEID="itz77"/>
</mets:div>
<mets:div ID="cwelh" ORDER="437" TYPE="LogicalMember">
<mets:fptr FILEID="itagh"/>
</mets:div>
<mets:div ID="y0dot" ORDER="438" TYPE="LogicalMember">
<mets:fptr FILEID="benqy"/>
</mets:div>
<mets:div ID="t32me" ORDER="439" TYPE="LogicalMember">
<mets:fptr FILEID="wglpb"/>
</mets:div>
<mets:div ID="gkror" ORDER="440" TYPE="LogicalMember">
<mets:fptr FILEID="sq1qt"/>
</mets:div>
<mets:div ID="sjzq4" ORDER="441" TYPE="LogicalMember">
<mets:fptr FILEID="rzcpw"/>
</mets:div>
<mets:div ID="xz79a" ORDER="442" TYPE="LogicalMember">
<mets:fptr FILEID="hoo0w"/>
</mets:div>
</mets:div>
```

which aren't represented (mostly the `postscript`)

**Comment by escowles** [comment]
@tpendragon I think the issue was that it's using the physical structure and ignoring the logical structure — #790 should fix that, but I want to add another test for that too.

**Comment by joycebcat** [comment]
@tpendragon @escowles There is structure inside the METS beyond the volumes.  In the snippet below there is the label "01" for the volume, but further down you will see "bookplate" "title page" and "preface" all subsections for this particular volume.

<mets:structMap TYPE="Logical" LABEL="Contents">
      <mets:div LABEL="" DMDID="object.dmd" TYPE="Work">
         <mets:div LABEL="01" TYPE="BoundArt" ID="v1log">
            <mets:div TYPE="LogicalMember" ORDER="1">
               <mets:mptr LOCTYPE="URL"
                  xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000001.mets"/>
            </mets:div>
            <mets:div LABEL="bookplate" TYPE="Section">
               <mets:div TYPE="LogicalMember" ORDER="2">
                  <mets:mptr LOCTYPE="URL"
                     xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000002.mets"
                  />
               </mets:div>
               <mets:div TYPE="LogicalMember" ORDER="3">
                  <mets:mptr LOCTYPE="URL"
                     xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000003.mets"
                  />
               </mets:div>
               <mets:div TYPE="LogicalMember" ORDER="4">
                  <mets:mptr LOCTYPE="URL"
                     xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000004.mets"
                  />
               </mets:div>
            </mets:div>
            <mets:div LABEL="title page" TYPE="Section">
               <mets:div TYPE="LogicalMember" ORDER="5">
                  <mets:mptr LOCTYPE="URL"
                     xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000005.mets"
                  />
               </mets:div>
               <mets:div TYPE="LogicalMember" ORDER="6">
                  <mets:mptr LOCTYPE="URL"
                     xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000006.mets"
                  />
               </mets:div>
            </mets:div>
            <mets:div LABEL="preface" TYPE="Section">
               <mets:div TYPE="LogicalMember" ORDER="7">
                  <mets:mptr LOCTYPE="URL"
                     xlink:href="http://diglib.princeton.edu/images/pudl0058/616086/01/00000007.mets"
                  />
               </mets:div>

**Comment by joycebcat** [comment]
@tpendragon I can confirm that you are indeed pulling only the physical structure and not the logical structure as @escowles hypothesized because I see all the elaborate physical structure of Biblia Latina (with the black cover) present.

**Comment by escowles** [comment]
I've opened PR #790 for using the logical structure if present.  When using this code locally, I see the logical structure for this item instead of the flat physical structure.
