### ISSUE TITLE
Bound-with (Sammelband) cleanup

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#788]
The object in Plum which displays under the title "Remorse a tragedy in five acts" is a bound with (BW).  It displays in the PUDL under the title "Christabel, &c" with a note "With: Remorse : a tragedy in five acts. -- London : W. Pople, 1813."

Plum has associated the whole digital object with bib id: 2893853.  In actuality a section of the digital object belongs to bib id 2893853 and another section to bib id 3023901.

**Comment by tpendragon** [comment]
@escowles @jpstroop If I remember right, we decided we'd just have to manually go in and fix the sammelbands, yeah? That there wasn't enough information in the METS to automatically reason about what to do?

**Comment by jpstroop** [comment]
Yes, that's correct. We have no way of knowing where one stops and the next begins. There is a small number for which we might be able to rely on naming conventions (i.e. `bibid_bibid.mets`), but I don't think it's worth the effort.

**Comment by joycebcat** [comment]
OK, So can I try this out?  What would I need to do, or is something that needs to be done when the images are imported?

**Comment by jpstroop** [comment]
These are going to probably need to be reingested manually. Start a list here:

 * http://plum.princeton.edu/concern/scanned_resources/p5712n7160
