### ISSUE TITLE
Vols. > 1 lack a thumbnail

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#789]
This is what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/999701/19733669/adb5e55c-9b72-11e6-8be1-d5f00fb9d2de.png)

**Comment by jpstroop** [comment]
I think this is on MVWs

**Comment by jpstroop** [comment]
I think I figured this out. See http://lib-plum1.princeton.edu/concern/multi_volume_works/p3t945w29z

Volumes > 1 aren't don't have a thumbnail set. @escowles could the ingest task just set this to the first image of each vol? 

Also, I know know if threre's a way we could do this retrospectively, but it would be nice.

**Comment by escowles** [comment]
OK, this seems like an easy fix going forward: at the end of ingesting files, we can set the thumbnail to the first file if there's not a thumbnail set.  For the existing volumes, it should be easy to find the ones with no thumbnail set and set it to the first fileset.
