### ISSUE TITLE
Metadata display - date created

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#791]
Turning the date from the MARC data into a month-day-year in the display isn't ideal.

1937
becomes
01/01/1937

There may be cases with manuscripts where we have more specific date, but usually we will have a year or something less specific than a year.

**Comment by jpstroop** [comment]
I think the display date should just be part of the whole publication statement, which is `pub_created_display`

We should continue to use `pub_date_start_sort` for sorting and indexing (unless there's another machine date field I'm not finding).
