### ISSUE TITLE
Metadata display - call numbers

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#793]
It appears that call numbers for all copies of an object are being displayed.  Clarissa is a particularly wild example: 
RHT 18th-447
30.3.3
30.3.4
2015-0801N
30.3.2
RHT 18th-446
30.3.1
Electronic Resource
30.3.7
30.3.5
30.3.6

Since a lot of rare material is included in our digital library, knowing which copy is represented by the digital object is important because the separate copies will have a number of variations.  We have at least one occurrence in the PUDL of two separate digital objects which are covered by the same bib record because they are copies of the same thing.

**Comment by jpstroop** [comment]
See #794
