### ISSUE TITLE
Metadata display - location

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#794]
The location is not displaying.  This call number "30.3.3" isn't helpful without knowing what the location is.

(If multiple call numbers continue to be displayed, you can't separate the location into a separate element, or a viewer will not be able to tell which call number belongs with which location.)

**Comment by jpstroop** [comment]
May need some help from @tampakis on this one.

It could be a concatenation of `location_display` and `call_number_display`, but both are [potentially multivalued](https://bibdata.princeton.edu/bibliographic/4609321/solr). I see two alternatives. Multiple values probably won't come up too often, but I wonder so wonder if we should allow for an override in Plum? Either that or we'd need to allow users to select which holding was digitized. Neither seems great...

**Comment by joycebcat** [comment]
We (meaning me) are starting to push harder for folks to make their sites live.  The lack of location will become an issue as soon as they stop configuring and start focusing on what the user will see.
