### ISSUE TITLE
Metadata display - more information tab

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#795]
When I click open the "more information" tab in the image viewer box to the right, it shows the labels for various data elements, but no data values.  Clicking doesn't take me anywhere either.  This tab doesn't seem to actually do anything.

**Comment by tpendragon** [comment]
Yeah, this is a bug that's going to fixed in the viewer shortly.

**Comment by jpstroop** [comment]
Mostly closed, still broken for MVWs. Closing in favor of #917.
