### ISSUE TITLE
Ingest errors

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#796]
There were about 100 records that had errors when ingesting.  The vast majority of these were metadata errors: a few that didn't have a bib record in the METS but mostly missing/suppressed bib records.  There were also a handful of errors with files that were missing or otherwise couldn't be processed.

I've created a spreadsheet to track these errors so we can figure out what do about them: https://docs.google.com/spreadsheets/d/1qb3Td4GjhHRwhrsVJKNx_er1Kz4ASOXORl1KBJHCTfc/edit

**Comment by jpstroop** [comment]
@joycebcat would you mind having a quick glance at these? I'm not sure why records for stuff in the PUDL would be suppressed, but that seems to be the case with most of the pudl0076 (Lapidus) items.

**Comment by joycebcat** [comment]
Unfortunately I wasn't involved with Lapidus at all and don't know what the history is with the bib records.  From looking at these, I think maybe the records were created in advance of the digital object being ready, but RB never went back to them and filled them out.  The fact that they were all created by a curator and not a cataloger and the fact that there are some duplicate records makes me reluctant to put my oar in what could have been a dispute within RB.  Could you please ask Don about these? (Or I will if you want me to)

**Comment by jpstroop** [comment]
They do exist and are suppressed though, right?

**Comment by jpstroop** [comment]
The pudl0076 errors were all fixed in December as of today 200 of 267 have loaded successfully.

**Comment by escowles** [comment]
Closing this old ticket — will keep tracking and validating the ingest.
