### ISSUE TITLE
Consider caching Manifests somewhere

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#797]
We do something similar with PDFs - maybe we can replicate that for manifests so they're only generated if it's really necessary? Relevant code in `app/values/resource_identifier.rb`

**Comment by tpendragon** [comment]
https://github.com/pulibrary/plum/compare/cached_manifests seems to work really well. Might be something we want to consider.

**Comment by jpstroop** [comment]
Are there any cons? Why wouldn't we do that?

I didn't know about `Rails.cache`, but was going to suggest stashing them in Solr as a string--we do this w/ LAE, but those Manifests are much smaller. This seems like a better approach as long as we have the right hooks to keep the cache valid.

**Comment by escowles** [comment]
+1 — probably much better than managing our own cache in Solr or on disk (might be good for the PDFs too?)

It looks like it handles a lot of AR and view updates automatically, but we'd probably just need to implement an updated timestamp to have it invalidate the manifests when the object changed: http://guides.rubyonrails.org/caching_with_rails.html#low-level-caching

**Comment by tpendragon** [comment]
Fortunately we're making sure that resource identifier is up to date since we're using it for caching PDFs to disk (the right move I think - storing a PDF in a cache might get messy.)

We'll probably want to install and set up rails to use memcached in production though - having an LRU in-memory cache will be quicker and self-maintaining, the only downside being it'll have to warm itself back up after a system reboot. We'll need a rake task to clear out the task too, and might want to consider wiping the cache between deploys.
