### ISSUE TITLE
Manifests need `logo` and rights statements

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#798]
See http://iiif.io/api/presentation/2.1/#rights-and-licensing-properties

For logo, something from here: https://github.com/pulibrary/pul_graphics/tree/master/pul/png

**Comment by jpstroop** [comment]
This will be important for cicognara.

**Comment by rlskoeser** [comment]
Having the rights statements in the manifests will be useful for CDH projects making use of PUL materials, so we can be sure we're using materials appropriately and not exposing or reusing content that we shouldn't.
