### ISSUE TITLE
2 up view in UV

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#803]
Sandy was asking how--pretty sure this was something we could do in UV, but I can't figure out how. Is it disabled?

**Comment by tpendragon** [comment]
You only get 2-up if the scanned resource is marked as paged.

**Comment by jpstroop** [comment]
OK. That might be something to add to the METS ingest script. Probably for everything except `TightBoundManuscript` and `RTLTightBoundManuscript`

**Comment by jpstroop** [comment]
Looks like this was done in 477bbfae53d1305152cb213cdea3d16dd8dc257b
