### ISSUE TITLE
Track Sidekiq failures

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#817]
A count of failed jobs is displayed in the Sidekiq dashboard, but there's no list to review which items didn't ingest successfully.  Try using https://github.com/mhfs/sidekiq-failures to track those.

**Comment by jpstroop** [comment]
@escowles Do we still want this? It seems pretty old and I wonder if it still works. Or did we get to the bottom of it earlier this week? See also #937

**Comment by escowles** [comment]
Yes, I think we can close this one — it looks like Sidekiq is putting jobs back into the queue and the failures number is just a count of how many failures, not a black hole.
