### ISSUE TITLE
Adjust worker configuration

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#818]
When the default queue (file ingest/characterization/derivatives) gets behind, it grows progressively larger as the ingest queue adds items to the queue faster than the workers can clear it.  Adjust the worker configuration to prevent this:

* Reduce the number of default queue worker threads so the system load doesn't cause as much slowdown?
* Move the default queue to the highest priority, and have ingest workers process those jobs if there are any waiting?

**Comment by jpstroop** [comment]
See also (and maybe do with) #936
