### ISSUE TITLE
Delete temp files after generating derivatives

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#821]
We currently queue an OCR job, but schedule it so low it never runs.  Should we just delete the temp file after generating derivatives, and assume we'll run a separate task to perform OCR later?

**Comment by jpstroop** [comment]
@escowles is this done?

**Comment by escowles** [comment]
I think this is obviated by storing master files outside of Fedora — we don't create local temp copies, so we don't need to delete them.
