### ISSUE TITLE
File manager: tab from label to label

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#826]
When I can't use the bulk label utility (e.g. when I want to key in "[cover]", "[pastedown]"), `tab` should let me jump from one label box to the next.

**Comment by tpendragon** [comment]
Usability issues here, because then there'd be no way to tab to the IIIF options or other hyperlinks. Maybe we need a "mode" selector, for switching to labels only?

**Comment by jpstroop** [comment]
Let's table it until someone besides me asks.
