### ISSUE TITLE
Parallel (Arabic) Titles not in Plum/Manifest/Pom

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#833]
E.g.: http://plum.princeton.edu/concern/scanned_resources/pdr26zb47k

**Comment by jpstroop** [comment]
I guess we ignore because it's in the label?

**Comment by jpstroop** [comment]
Hmm...not in the jsonld either: https://bibdata.princeton.edu/bibliographic/7849192/jsonld

**Comment by tpendragon** [comment]
Yeah, seems like a bibdata JSON-LD problem.
