### ISSUE TITLE
Upload from Google Drive

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#852]
There's a second use case for this that involves a small exhibit for RBSC and will come up before patron imaging is ready to switch. Can browse-everything support more than one source at a time?

**Comment by escowles** [comment]
Yes, I believe multiple providers can be configured, and each would show up as a separate tab in the Browse Everything file selector window.

**Comment by escowles** [comment]
Another use case for Google Drive: depending on the hardware used, it might be easiest for the Table of Contents scanning project to upload files to Google Drive instead of mounting the Isilon.
