### ISSUE TITLE
After ingesting images you should be able to alter the order of the pages that was assumed from ingest.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plum#9]

**Comment by terrellt** [comment]
https://github.com/pulibrary/pages-editor-mockup

**Comment by flyingzumwalt** [comment]
Blocked by projecthydra-labs/activefedora-aggregation#71 -- can't update ordering of members using member ids.

**Comment by flyingzumwalt** [comment]
Also related to projecthydra-labs/hydra-works#208
