### ISSUE TITLE
PUDL Items that should maybe be Scanned Maps?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#914]
@eliotjordan (and others):
`pudl0064` (Vandermaelen Atlas)
`pudl0070` (Paris Maps - probably not, but would be a nice feature; will do as `ScannedResource` for now)
`pudl0072` (Japanese Maps - probably not, but would be a nice feature; will do as `ScannedResource` for now)
`pudl0077` (NYC Map)
`pudl0115` (_Cedid atlas tercümesi_, the first Turkish atlas)
`pudl0116` (_Heinrich Berghaus’s Physikalischer Atlas_, the first “physical” atlas)
`pudl0124` (Atlas of NJ)

**Comment by eliotjordan** [comment]
For reference:
`pudl0064` http://arks.princeton.edu/ark:/88435/vh53ww48j
`pudl0070` http://arks.princeton.edu/ark:/88435/79407z45c (?)
`pudl0072` ? http://arks.princeton.edu/ark:/88435/6969z2077 (e.g. ?)
`pudl0077` ?
`pudl0115` http://arks.princeton.edu/ark:/88435/0v838195t
`pudl0116` http://arks.princeton.edu/ark:/88435/4m90dw87h
`pudl0124` http://arks.princeton.edu/ark:/88435/79407z45c

**Comment by jpstroop** [comment]
Heh, yeah, maybe not 72.
