### ISSUE TITLE
Lots of missing Jp2s

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#934]
http://plum.princeton.edu/catalog?_=1483696006670&f%5Bmember_of_collections_ssim%5D%5B%5D=McLoughlin+Publisher%E2%80%99s+Catalogs%2C+Advertising+Materials%2C+and+%E2%80%9CPublisher%E2%80%99s+Archives%E2%80%9D+Items&q=

**Comment by jpstroop** [comment]
Wider issue is my guess: http://plum.princeton.edu/catalog?_=1483696006670&f%5Bmember_of_collections_ssim%5D%5B%5D=Princeton+Digital+Library+of+Islamic+Manuscripts&page=32&q=

**Comment by jpstroop** [comment]
http://plum.princeton.edu/catalog?_=1483696006670&f%5Bmember_of_collections_ssim%5D%5B%5D=Japanese+Prints+and+Drawings+in+the+Cotsen+Collection&q=&sort=date_uploaded_dtsi+asc

**Comment by jpstroop** [comment]
http://plum.princeton.edu/catalog?_=1483696006670&f%5Bmember_of_collections_ssim%5D%5B%5D=East+Asian+Library+Digital+Bookshelf&page=6&q=&sort=date_uploaded_dtsi+asc

**Comment by jpstroop** [comment]
http://plum.princeton.edu/catalog?_=1483696006670&f%5Bmember_of_collections_ssim%5D%5B%5D=East+Asian+Library+Digital+Bookshelf&page=9&q=&sort=date_uploaded_dtsi+asc

**Comment by jpstroop** [comment]
http://plum.princeton.edu/catalog?_=1483696006670&f%5Bmember_of_collections_ssim%5D%5B%5D=Yemeni+Manuscript+Digitization+Initiative&page=2&q=&sort=date_uploaded_dtsi+asc

**Comment by escowles** [comment]
I think this is happening because the default queue is backed up (35K items waiting right now).  So the objects have been created and indexed, the TIFFs have been loaded, but the JP2s haven't been generated yet.  I'm going to stop the ingest queue to let the default queue catch up.

**Comment by escowles** [comment]
But this has been a consistent problem, where the default queue can typically keep up.  But as soon as it gets behind it gets further and further behind.  Maybe we should have only one ingest worker?

**Comment by jpstroop** [comment]
There are a few other tickets about this. Seems if we had another worker machine that that was just dedicated to the default queue, would that help since one job is copying to the Islion and the other to the image server (correct?)?

**Comment by jpstroop** [comment]
Would be nice if we could automate throttling down the ingest queue when the default queue falls behind

**Comment by escowles** [comment]
We were going to setup lib-proc6 as a third worker machine in part to address this issue, but got stuck on Xenial/Trusty incompatibilities.  I agree it would be best if the ingest workers would just grab jobs from the default queue if there were any to avoid this.  I can see what our options are there.

**Comment by tpendragon** [comment]
We can just adjust priority so default is above ingest, if derivatives are more important than ingest.

**Comment by jpstroop** [comment]
These issues are documented in other tickets. Closing.
