### ISSUE TITLE
Error when entering workflow note without state change

### ISSUE THREAD

**Issue by escowles** [pulibrary/plum#946]
PowerConverter::ConversionError in CurationConcerns::WorkflowActionsController#update
Unable to convert false to 'sipity_action' (scope: #<Sipity::Workflow id: 1, name: "book_works", label: "Book Works", description: nil, created_at: "2017-01-10 18:48:18", updated_at: "2017-01-10 18:48:18">).

**Comment by eliotjordan** [comment]
This looks like it might be a bug in CurationConcerns. On the plum end, we could disable the workflow text box until a state button is selected.
