### ISSUE TITLE
Character encoding in UV

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#948]
Assuming this is a font problem and not a character encoding problem:

<img width="1311" alt="screen shot 2017-01-11 at 10 58 50 pm" src="https://cloud.githubusercontent.com/assets/999701/21876537/bc7d86aa-d851-11e6-9c2d-30222485fdef.png">

Here's the item:
https://plum.princeton.edu/concern/scanned_resources/p0c484h74c

**Comment by tpendragon** [comment]
Closed as a duplicate of #1122.

**Comment by tpendragon** [comment]
Closed as a duplicate of #1122
