### ISSUE TITLE
Should we have multiple sipity workflows?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#949]
Should plum have two workflows, one for 'books' and one for geo works? Or should it have a single workflow.

https://github.com/pulibrary/plum/tree/sipity-workflow/config/workflows

At this point, both workflows are the same, but that might change in the future. Also, including both allows for finer-grained control over notifications. Geo-work editors will probably not want notifications about changes to book objects they can't view. And vice versa. On the other hand, a single workflow is simpler. At least to start.

**Comment by jpstroop** [comment]
FWIW, I'm confident that we will need to support multiple workflows eventually, but it doesn't have to be a priority now. Let's just not tie our hands.

**Comment by escowles** [comment]
So it probably makes sense to keep the two workflows, even if they are the same, to make that easier to do later.

**Comment by jpstroop** [comment]
E.g, I think even the flow for Archives might be different from Pom, and imagine LAE and Geo will be different as well.

**Comment by eliotjordan** [comment]
Closing this issue now the the sipity PR is merged.
