### ISSUE TITLE
Leases and single use links

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#953]
Patron digitization would like this, or some other solution for sharing otherwise private content with users without requiring that they sign up for an account.

**Comment by jpstroop** [comment]
After a visit to the archives yesterday, it sounds like leases are more analogous to what they currently do w/ Google Drive than single use links.

**Comment by escowles** [comment]
That's good — I believe the support for leases/embargoes is there in CC now, and we would just need to update our forms to support it.

**Comment by jpstroop** [comment]
Oh, even better.
