### ISSUE TITLE
Add language codes to bib records 008

### ISSUE THREAD

**Issue by tampakis** [pulibrary/plum#966]
@joycebcat, these 4 records don't have language codes in the 008, causing the language value to be null in the jsonld. Would it be ok to add them?
https://bibdata.princeton.edu/bibliographic/3394549/jsonld
https://bibdata.princeton.edu/bibliographic/2521882/jsonld
https://bibdata.princeton.edu/bibliographic/5183524/jsonld
https://bibdata.princeton.edu/bibliographic/7307782/jsonld

**Comment by joycebcat** [comment]
They were kind of a mixed bag regarding codes.  I fixed them all in V.

**Comment by jpstroop** [comment]
Thank you!
