### ISSUE TITLE
viewingHint and viewingDirection in collections

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/plum#992]
E.g. https://plum.princeton.edu/collections/p9g54zg95b/manifest

![image](https://cloud.githubusercontent.com/assets/999701/22587574/365062f6-e9d0-11e6-9820-92d2d287a357.png)

Any particular reason? One less thing to serialize, and really only need `viewingHint`, I think, when the member is a collection and the value is `individuals` or `continuous`

**Comment by tpendragon** [comment]
The same builder builds id/type/label/viewingHint/viewingDirection. It was just easier.
