### ISSUE TITLE
pom search results 

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/plum#996]
In pom, the searching doesn't work as expected.  I was working inside the Islamic mss collection.

I was trying to find a particular object which is titled "Kitab al-Kashif li-dhawi al-uqul an maani al-Kafil bi-nayl al-sul"

kitab = 132 results
kitab al-kashif = 130
kitab kashif = 2
kitab al-kashif li-dhawi = 157

The numbers are changing right now--maybe it is still ingesting and will settle down later.  I can't cross-test easily in another collection because I don't have enough material in them.

**Comment by tpendragon** [comment]
Moved to https://github.com/pulibrary/pomegranate/issues/219
